/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ClearLegacyStudentsRequestDto,
  ClearLegacyStudentsResponseDto,
  ImportLegacyStudentsRequestDto,
  ImportLegacyStudentsResponseDto,
  LegacyStudentImportControllerFindAllParams,
  ListLegacyStudentsResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const legacyStudentImportControllerImportCsv = (
  importLegacyStudentsRequestDto: ImportLegacyStudentsRequestDto,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, importLegacyStudentsRequestDto.file);

  return service<ImportLegacyStudentsResponseDto>({
    url: `/legacy-student-import/import`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
    signal,
  });
};

export const getLegacyStudentImportControllerImportCsvMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof legacyStudentImportControllerImportCsv>>,
    TError,
    { data: ImportLegacyStudentsRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof legacyStudentImportControllerImportCsv>>,
  TError,
  { data: ImportLegacyStudentsRequestDto },
  TContext
> => {
  const mutationKey = ['legacyStudentImportControllerImportCsv'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof legacyStudentImportControllerImportCsv>>,
    { data: ImportLegacyStudentsRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return legacyStudentImportControllerImportCsv(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LegacyStudentImportControllerImportCsvMutationResult = NonNullable<
  Awaited<ReturnType<typeof legacyStudentImportControllerImportCsv>>
>;
export type LegacyStudentImportControllerImportCsvMutationBody = ImportLegacyStudentsRequestDto;
export type LegacyStudentImportControllerImportCsvMutationError = unknown;

export const useLegacyStudentImportControllerImportCsv = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof legacyStudentImportControllerImportCsv>>,
      TError,
      { data: ImportLegacyStudentsRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof legacyStudentImportControllerImportCsv>>,
  TError,
  { data: ImportLegacyStudentsRequestDto },
  TContext
> => {
  const mutationOptions = getLegacyStudentImportControllerImportCsvMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const legacyStudentImportControllerFindAll = (
  params?: LegacyStudentImportControllerFindAllParams,
  signal?: AbortSignal,
) => {
  return service<ListLegacyStudentsResponseDto>({ url: `/legacy-student-import`, method: 'GET', params, signal });
};

export const getLegacyStudentImportControllerFindAllQueryKey = (
  params?: LegacyStudentImportControllerFindAllParams,
) => {
  return [`/legacy-student-import`, ...(params ? [params] : [])] as const;
};

export const getLegacyStudentImportControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
  TError = unknown,
>(
  params?: LegacyStudentImportControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLegacyStudentImportControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>> = ({ signal }) =>
    legacyStudentImportControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LegacyStudentImportControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>
>;
export type LegacyStudentImportControllerFindAllQueryError = unknown;

export function useLegacyStudentImportControllerFindAll<
  TData = Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | LegacyStudentImportControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLegacyStudentImportControllerFindAll<
  TData = Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
  TError = unknown,
>(
  params?: LegacyStudentImportControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLegacyStudentImportControllerFindAll<
  TData = Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
  TError = unknown,
>(
  params?: LegacyStudentImportControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useLegacyStudentImportControllerFindAll<
  TData = Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>,
  TError = unknown,
>(
  params?: LegacyStudentImportControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof legacyStudentImportControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getLegacyStudentImportControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const legacyStudentImportControllerClear = (clearLegacyStudentsRequestDto: ClearLegacyStudentsRequestDto) => {
  return service<ClearLegacyStudentsResponseDto>({
    url: `/legacy-student-import/clear`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: clearLegacyStudentsRequestDto,
  });
};

export const getLegacyStudentImportControllerClearMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof legacyStudentImportControllerClear>>,
    TError,
    { data: ClearLegacyStudentsRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof legacyStudentImportControllerClear>>,
  TError,
  { data: ClearLegacyStudentsRequestDto },
  TContext
> => {
  const mutationKey = ['legacyStudentImportControllerClear'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof legacyStudentImportControllerClear>>,
    { data: ClearLegacyStudentsRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return legacyStudentImportControllerClear(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LegacyStudentImportControllerClearMutationResult = NonNullable<
  Awaited<ReturnType<typeof legacyStudentImportControllerClear>>
>;
export type LegacyStudentImportControllerClearMutationBody = ClearLegacyStudentsRequestDto;
export type LegacyStudentImportControllerClearMutationError = unknown;

export const useLegacyStudentImportControllerClear = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof legacyStudentImportControllerClear>>,
      TError,
      { data: ClearLegacyStudentsRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof legacyStudentImportControllerClear>>,
  TError,
  { data: ClearLegacyStudentsRequestDto },
  TContext
> => {
  const mutationOptions = getLegacyStudentImportControllerClearMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
