/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * App Service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  CreateVanDto,
  CreateVanResponseDto,
  DetailVansResponseDto,
  ListVansResponseDto,
  UpdateVanDto,
  UpdateVanResponseDto,
  VanControllerFindAllParams,
  VanControllerFindOneParams,
} from '../app.schemas';

import service from '../../../services/index';

export const vanControllerCreate = (createVanDto: CreateVanDto, signal?: AbortSignal) => {
  return service<CreateVanResponseDto>({
    url: `/van`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createVanDto,
    signal,
  });
};

export const getVanControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vanControllerCreate>>,
    TError,
    { data: CreateVanDto },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof vanControllerCreate>>, TError, { data: CreateVanDto }, TContext> => {
  const mutationKey = ['vanControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof vanControllerCreate>>, { data: CreateVanDto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return vanControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VanControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof vanControllerCreate>>>;
export type VanControllerCreateMutationBody = CreateVanDto;
export type VanControllerCreateMutationError = unknown;

export const useVanControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vanControllerCreate>>,
      TError,
      { data: CreateVanDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof vanControllerCreate>>, TError, { data: CreateVanDto }, TContext> => {
  const mutationOptions = getVanControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const vanControllerFindAll = (params?: VanControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListVansResponseDto>({ url: `/van`, method: 'GET', params, signal });
};

export const getVanControllerFindAllQueryKey = (params?: VanControllerFindAllParams) => {
  return [`/van`, ...(params ? [params] : [])] as const;
};

export const getVanControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof vanControllerFindAll>>,
  TError = unknown,
>(
  params?: VanControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindAll>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVanControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vanControllerFindAll>>> = ({ signal }) =>
    vanControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof vanControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VanControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof vanControllerFindAll>>>;
export type VanControllerFindAllQueryError = unknown;

export function useVanControllerFindAll<TData = Awaited<ReturnType<typeof vanControllerFindAll>>, TError = unknown>(
  params: undefined | VanControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vanControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof vanControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVanControllerFindAll<TData = Awaited<ReturnType<typeof vanControllerFindAll>>, TError = unknown>(
  params?: VanControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vanControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof vanControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVanControllerFindAll<TData = Awaited<ReturnType<typeof vanControllerFindAll>>, TError = unknown>(
  params?: VanControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useVanControllerFindAll<TData = Awaited<ReturnType<typeof vanControllerFindAll>>, TError = unknown>(
  params?: VanControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVanControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const vanControllerFindOne = (id: string, params?: VanControllerFindOneParams, signal?: AbortSignal) => {
  return service<DetailVansResponseDto>({ url: `/van/${id}`, method: 'GET', params, signal });
};

export const getVanControllerFindOneQueryKey = (id?: string, params?: VanControllerFindOneParams) => {
  return [`/van/${id}`, ...(params ? [params] : [])] as const;
};

export const getVanControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof vanControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: VanControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindOne>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVanControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vanControllerFindOne>>> = ({ signal }) =>
    vanControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof vanControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VanControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof vanControllerFindOne>>>;
export type VanControllerFindOneQueryError = unknown;

export function useVanControllerFindOne<TData = Awaited<ReturnType<typeof vanControllerFindOne>>, TError = unknown>(
  id: string,
  params: undefined | VanControllerFindOneParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vanControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof vanControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVanControllerFindOne<TData = Awaited<ReturnType<typeof vanControllerFindOne>>, TError = unknown>(
  id: string,
  params?: VanControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vanControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof vanControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVanControllerFindOne<TData = Awaited<ReturnType<typeof vanControllerFindOne>>, TError = unknown>(
  id: string,
  params?: VanControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useVanControllerFindOne<TData = Awaited<ReturnType<typeof vanControllerFindOne>>, TError = unknown>(
  id: string,
  params?: VanControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof vanControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVanControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const vanControllerUpdate = (id: string, updateVanDto: UpdateVanDto) => {
  return service<UpdateVanResponseDto>({
    url: `/van/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateVanDto,
  });
};

export const getVanControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vanControllerUpdate>>,
    TError,
    { id: string; data: UpdateVanDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vanControllerUpdate>>,
  TError,
  { id: string; data: UpdateVanDto },
  TContext
> => {
  const mutationKey = ['vanControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vanControllerUpdate>>,
    { id: string; data: UpdateVanDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return vanControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VanControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof vanControllerUpdate>>>;
export type VanControllerUpdateMutationBody = UpdateVanDto;
export type VanControllerUpdateMutationError = unknown;

export const useVanControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vanControllerUpdate>>,
      TError,
      { id: string; data: UpdateVanDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof vanControllerUpdate>>,
  TError,
  { id: string; data: UpdateVanDto },
  TContext
> => {
  const mutationOptions = getVanControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const vanControllerRemove = (id: string) => {
  return service<ActionResponseDto>({ url: `/van/${id}`, method: 'DELETE' });
};

export const getVanControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof vanControllerRemove>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof vanControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['vanControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof vanControllerRemove>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return vanControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VanControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof vanControllerRemove>>>;

export type VanControllerRemoveMutationError = unknown;

export const useVanControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof vanControllerRemove>>, TError, { id: string }, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof vanControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getVanControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const vanControllerDeactivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/van/${id}/deactivate`, method: 'DELETE' });
};

export const getVanControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof vanControllerDeactivate>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof vanControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['vanControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof vanControllerDeactivate>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return vanControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VanControllerDeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof vanControllerDeactivate>>>;

export type VanControllerDeactivateMutationError = unknown;

export const useVanControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vanControllerDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof vanControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getVanControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const vanControllerActivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/van/${id}/activate`, method: 'PATCH' });
};

export const getVanControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof vanControllerActivate>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof vanControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['vanControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof vanControllerActivate>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return vanControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VanControllerActivateMutationResult = NonNullable<Awaited<ReturnType<typeof vanControllerActivate>>>;

export type VanControllerActivateMutationError = unknown;

export const useVanControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof vanControllerActivate>>, TError, { id: string }, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof vanControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getVanControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
