/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import type {
  AdminChangePasswordRequestDto,
  AdminChangePasswordResponseDto,
  AdminCreatePasswordRequestDto,
  AdminCreatePasswordResponseDto,
  AdminForgotPasswordRequestDto,
  AdminForgotPasswordResponseDto,
  AdminResetPasswordRequestDto,
  AdminResetPasswordResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const adminAuthPasswordControllerChangePassword = (
  adminChangePasswordRequestDto: AdminChangePasswordRequestDto,
  signal?: AbortSignal,
) => {
  return service<AdminChangePasswordResponseDto>({
    url: `/admin/auth/password/change`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminChangePasswordRequestDto,
    signal,
  });
};

export const getAdminAuthPasswordControllerChangePasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthPasswordControllerChangePassword>>,
    TError,
    { data: AdminChangePasswordRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthPasswordControllerChangePassword>>,
  TError,
  { data: AdminChangePasswordRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthPasswordControllerChangePassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthPasswordControllerChangePassword>>,
    { data: AdminChangePasswordRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthPasswordControllerChangePassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthPasswordControllerChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthPasswordControllerChangePassword>>
>;
export type AdminAuthPasswordControllerChangePasswordMutationBody = AdminChangePasswordRequestDto;
export type AdminAuthPasswordControllerChangePasswordMutationError = unknown;

export const useAdminAuthPasswordControllerChangePassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthPasswordControllerChangePassword>>,
      TError,
      { data: AdminChangePasswordRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthPasswordControllerChangePassword>>,
  TError,
  { data: AdminChangePasswordRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthPasswordControllerChangePasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthPasswordControllerForgotPassword = (
  adminForgotPasswordRequestDto: AdminForgotPasswordRequestDto,
  signal?: AbortSignal,
) => {
  return service<AdminForgotPasswordResponseDto>({
    url: `/admin/auth/password/forgot`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminForgotPasswordRequestDto,
    signal,
  });
};

export const getAdminAuthPasswordControllerForgotPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthPasswordControllerForgotPassword>>,
    TError,
    { data: AdminForgotPasswordRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthPasswordControllerForgotPassword>>,
  TError,
  { data: AdminForgotPasswordRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthPasswordControllerForgotPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthPasswordControllerForgotPassword>>,
    { data: AdminForgotPasswordRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthPasswordControllerForgotPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthPasswordControllerForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthPasswordControllerForgotPassword>>
>;
export type AdminAuthPasswordControllerForgotPasswordMutationBody = AdminForgotPasswordRequestDto;
export type AdminAuthPasswordControllerForgotPasswordMutationError = unknown;

export const useAdminAuthPasswordControllerForgotPassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthPasswordControllerForgotPassword>>,
      TError,
      { data: AdminForgotPasswordRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthPasswordControllerForgotPassword>>,
  TError,
  { data: AdminForgotPasswordRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthPasswordControllerForgotPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthPasswordControllerResetPassword = (
  adminResetPasswordRequestDto: AdminResetPasswordRequestDto,
  signal?: AbortSignal,
) => {
  return service<AdminResetPasswordResponseDto>({
    url: `/admin/auth/password/reset`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminResetPasswordRequestDto,
    signal,
  });
};

export const getAdminAuthPasswordControllerResetPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthPasswordControllerResetPassword>>,
    TError,
    { data: AdminResetPasswordRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthPasswordControllerResetPassword>>,
  TError,
  { data: AdminResetPasswordRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthPasswordControllerResetPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthPasswordControllerResetPassword>>,
    { data: AdminResetPasswordRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthPasswordControllerResetPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthPasswordControllerResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthPasswordControllerResetPassword>>
>;
export type AdminAuthPasswordControllerResetPasswordMutationBody = AdminResetPasswordRequestDto;
export type AdminAuthPasswordControllerResetPasswordMutationError = unknown;

export const useAdminAuthPasswordControllerResetPassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthPasswordControllerResetPassword>>,
      TError,
      { data: AdminResetPasswordRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthPasswordControllerResetPassword>>,
  TError,
  { data: AdminResetPasswordRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthPasswordControllerResetPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthPasswordControllerCreatePassword = (
  adminCreatePasswordRequestDto: AdminCreatePasswordRequestDto,
  signal?: AbortSignal,
) => {
  return service<AdminCreatePasswordResponseDto>({
    url: `/admin/auth/password/create`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminCreatePasswordRequestDto,
    signal,
  });
};

export const getAdminAuthPasswordControllerCreatePasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthPasswordControllerCreatePassword>>,
    TError,
    { data: AdminCreatePasswordRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthPasswordControllerCreatePassword>>,
  TError,
  { data: AdminCreatePasswordRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthPasswordControllerCreatePassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthPasswordControllerCreatePassword>>,
    { data: AdminCreatePasswordRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthPasswordControllerCreatePassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthPasswordControllerCreatePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthPasswordControllerCreatePassword>>
>;
export type AdminAuthPasswordControllerCreatePasswordMutationBody = AdminCreatePasswordRequestDto;
export type AdminAuthPasswordControllerCreatePasswordMutationError = unknown;

export const useAdminAuthPasswordControllerCreatePassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthPasswordControllerCreatePassword>>,
      TError,
      { data: AdminCreatePasswordRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthPasswordControllerCreatePassword>>,
  TError,
  { data: AdminCreatePasswordRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthPasswordControllerCreatePasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
