/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AttendanceControllerListDaysParams,
  AttendanceControllerStudentHistoryParams,
  AttendanceSummaryResponseDto,
  BulkUpsertAttendanceRecordsDto,
  BulkUpsertAttendanceRecordsResponseDto,
  ListAttendanceDaysResponseDto,
  StudentAttendanceHistoryResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const attendanceControllerListDays = (params: AttendanceControllerListDaysParams, signal?: AbortSignal) => {
  return service<ListAttendanceDaysResponseDto>({ url: `/attendance/days`, method: 'GET', params, signal });
};

export const getAttendanceControllerListDaysQueryKey = (params?: AttendanceControllerListDaysParams) => {
  return [`/attendance/days`, ...(params ? [params] : [])] as const;
};

export const getAttendanceControllerListDaysQueryOptions = <
  TData = Awaited<ReturnType<typeof attendanceControllerListDays>>,
  TError = unknown,
>(
  params: AttendanceControllerListDaysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerListDays>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAttendanceControllerListDaysQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerListDays>>> = ({ signal }) =>
    attendanceControllerListDays(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof attendanceControllerListDays>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AttendanceControllerListDaysQueryResult = NonNullable<
  Awaited<ReturnType<typeof attendanceControllerListDays>>
>;
export type AttendanceControllerListDaysQueryError = unknown;

export function useAttendanceControllerListDays<
  TData = Awaited<ReturnType<typeof attendanceControllerListDays>>,
  TError = unknown,
>(
  params: AttendanceControllerListDaysParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerListDays>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerListDays>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerListDays>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAttendanceControllerListDays<
  TData = Awaited<ReturnType<typeof attendanceControllerListDays>>,
  TError = unknown,
>(
  params: AttendanceControllerListDaysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerListDays>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerListDays>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerListDays>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAttendanceControllerListDays<
  TData = Awaited<ReturnType<typeof attendanceControllerListDays>>,
  TError = unknown,
>(
  params: AttendanceControllerListDaysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerListDays>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAttendanceControllerListDays<
  TData = Awaited<ReturnType<typeof attendanceControllerListDays>>,
  TError = unknown,
>(
  params: AttendanceControllerListDaysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerListDays>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAttendanceControllerListDaysQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const attendanceControllerBulkUpsert = (
  attendanceDayId: string,
  bulkUpsertAttendanceRecordsDto: BulkUpsertAttendanceRecordsDto,
  signal?: AbortSignal,
) => {
  return service<BulkUpsertAttendanceRecordsResponseDto>({
    url: `/attendance/days/${attendanceDayId}/records`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: bulkUpsertAttendanceRecordsDto,
    signal,
  });
};

export const getAttendanceControllerBulkUpsertMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof attendanceControllerBulkUpsert>>,
    TError,
    { attendanceDayId: string; data: BulkUpsertAttendanceRecordsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof attendanceControllerBulkUpsert>>,
  TError,
  { attendanceDayId: string; data: BulkUpsertAttendanceRecordsDto },
  TContext
> => {
  const mutationKey = ['attendanceControllerBulkUpsert'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof attendanceControllerBulkUpsert>>,
    { attendanceDayId: string; data: BulkUpsertAttendanceRecordsDto }
  > = (props) => {
    const { attendanceDayId, data } = props ?? {};

    return attendanceControllerBulkUpsert(attendanceDayId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AttendanceControllerBulkUpsertMutationResult = NonNullable<
  Awaited<ReturnType<typeof attendanceControllerBulkUpsert>>
>;
export type AttendanceControllerBulkUpsertMutationBody = BulkUpsertAttendanceRecordsDto;
export type AttendanceControllerBulkUpsertMutationError = unknown;

export const useAttendanceControllerBulkUpsert = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof attendanceControllerBulkUpsert>>,
      TError,
      { attendanceDayId: string; data: BulkUpsertAttendanceRecordsDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof attendanceControllerBulkUpsert>>,
  TError,
  { attendanceDayId: string; data: BulkUpsertAttendanceRecordsDto },
  TContext
> => {
  const mutationOptions = getAttendanceControllerBulkUpsertMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const attendanceControllerSummary = (attendanceDayId: string, signal?: AbortSignal) => {
  return service<AttendanceSummaryResponseDto>({
    url: `/attendance/days/${attendanceDayId}/summary`,
    method: 'GET',
    signal,
  });
};

export const getAttendanceControllerSummaryQueryKey = (attendanceDayId?: string) => {
  return [`/attendance/days/${attendanceDayId}/summary`] as const;
};

export const getAttendanceControllerSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof attendanceControllerSummary>>,
  TError = unknown,
>(
  attendanceDayId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerSummary>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAttendanceControllerSummaryQueryKey(attendanceDayId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerSummary>>> = ({ signal }) =>
    attendanceControllerSummary(attendanceDayId, signal);

  return { queryKey, queryFn, enabled: !!attendanceDayId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof attendanceControllerSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AttendanceControllerSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof attendanceControllerSummary>>
>;
export type AttendanceControllerSummaryQueryError = unknown;

export function useAttendanceControllerSummary<
  TData = Awaited<ReturnType<typeof attendanceControllerSummary>>,
  TError = unknown,
>(
  attendanceDayId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerSummary>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAttendanceControllerSummary<
  TData = Awaited<ReturnType<typeof attendanceControllerSummary>>,
  TError = unknown,
>(
  attendanceDayId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerSummary>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerSummary>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAttendanceControllerSummary<
  TData = Awaited<ReturnType<typeof attendanceControllerSummary>>,
  TError = unknown,
>(
  attendanceDayId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAttendanceControllerSummary<
  TData = Awaited<ReturnType<typeof attendanceControllerSummary>>,
  TError = unknown,
>(
  attendanceDayId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAttendanceControllerSummaryQueryOptions(attendanceDayId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const attendanceControllerStudentHistory = (
  studentId: string,
  params: AttendanceControllerStudentHistoryParams,
  signal?: AbortSignal,
) => {
  return service<StudentAttendanceHistoryResponseDto>({
    url: `/attendance/student/${studentId}`,
    method: 'GET',
    params,
    signal,
  });
};

export const getAttendanceControllerStudentHistoryQueryKey = (
  studentId?: string,
  params?: AttendanceControllerStudentHistoryParams,
) => {
  return [`/attendance/student/${studentId}`, ...(params ? [params] : [])] as const;
};

export const getAttendanceControllerStudentHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
  TError = unknown,
>(
  studentId: string,
  params: AttendanceControllerStudentHistoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerStudentHistory>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAttendanceControllerStudentHistoryQueryKey(studentId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerStudentHistory>>> = ({ signal }) =>
    attendanceControllerStudentHistory(studentId, params, signal);

  return { queryKey, queryFn, enabled: !!studentId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AttendanceControllerStudentHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof attendanceControllerStudentHistory>>
>;
export type AttendanceControllerStudentHistoryQueryError = unknown;

export function useAttendanceControllerStudentHistory<
  TData = Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
  TError = unknown,
>(
  studentId: string,
  params: AttendanceControllerStudentHistoryParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerStudentHistory>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerStudentHistory>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAttendanceControllerStudentHistory<
  TData = Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
  TError = unknown,
>(
  studentId: string,
  params: AttendanceControllerStudentHistoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerStudentHistory>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerStudentHistory>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAttendanceControllerStudentHistory<
  TData = Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
  TError = unknown,
>(
  studentId: string,
  params: AttendanceControllerStudentHistoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerStudentHistory>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAttendanceControllerStudentHistory<
  TData = Awaited<ReturnType<typeof attendanceControllerStudentHistory>>,
  TError = unknown,
>(
  studentId: string,
  params: AttendanceControllerStudentHistoryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerStudentHistory>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAttendanceControllerStudentHistoryQueryOptions(studentId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
