/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * App Service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AttendanceSheetFilterDto,
  AttendanceSheetPreviewResponseDto,
  CancelCardPrintRequestResponseDto,
  CountCardPrintRequestsResponseDto,
  CreateCardPrintRequestDto,
  CreateCardPrintRequestResponseDto,
  IdCardFilterDto,
  IdCardPreviewResponseDto,
  ListCardPrintRequestsResponseDto,
  PrintingControllerCountCardPrintRequestsParams,
  PrintingControllerListCardPrintRequestsParams,
  PrintingControllerPreviewAttendanceSheetsParams,
  PrintingControllerPreviewIdCardsParams,
  PrintingControllerPreviewSittingSlipsParams,
  ProcessCardPrintRequestsDto,
  ProcessCardPrintRequestsResponseDto,
  SittingSlipFilterDto,
  SittingSlipPreviewResponseDto,
  VerificationSlipFilterDto,
  VerificationSlipPreviewResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const printingControllerPreviewIdCards = (
  params: PrintingControllerPreviewIdCardsParams,
  signal?: AbortSignal,
) => {
  return service<IdCardPreviewResponseDto>({ url: `/printing/id-cards/preview`, method: 'GET', params, signal });
};

export const getPrintingControllerPreviewIdCardsQueryKey = (params?: PrintingControllerPreviewIdCardsParams) => {
  return [`/printing/id-cards/preview`, ...(params ? [params] : [])] as const;
};

export const getPrintingControllerPreviewIdCardsQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewIdCardsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCards>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerPreviewIdCardsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerPreviewIdCards>>> = ({ signal }) =>
    printingControllerPreviewIdCards(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerPreviewIdCardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerPreviewIdCards>>
>;
export type PrintingControllerPreviewIdCardsQueryError = unknown;

export function usePrintingControllerPreviewIdCards<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewIdCardsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCards>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewIdCards>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewIdCards<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewIdCardsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCards>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewIdCards>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewIdCards<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewIdCardsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCards>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerPreviewIdCards<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCards>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewIdCardsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCards>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerPreviewIdCardsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerPreviewIdCardDesign = (signal?: AbortSignal) => {
  return service<void>({ url: `/printing/id-cards/preview-design`, method: 'GET', signal });
};

export const getPrintingControllerPreviewIdCardDesignQueryKey = () => {
  return [`/printing/id-cards/preview-design`] as const;
};

export const getPrintingControllerPreviewIdCardDesignQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerPreviewIdCardDesignQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>> = ({ signal }) =>
    printingControllerPreviewIdCardDesign(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerPreviewIdCardDesignQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>
>;
export type PrintingControllerPreviewIdCardDesignQueryError = unknown;

export function usePrintingControllerPreviewIdCardDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewIdCardDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewIdCardDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerPreviewIdCardDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewIdCardDesign>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerPreviewIdCardDesignQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerGenerateIdCards = (idCardFilterDto: IdCardFilterDto, signal?: AbortSignal) => {
  return service<void>({
    url: `/printing/id-cards/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: idCardFilterDto,
    signal,
  });
};

export const getPrintingControllerGenerateIdCardsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerGenerateIdCards>>,
    TError,
    { data: IdCardFilterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerGenerateIdCards>>,
  TError,
  { data: IdCardFilterDto },
  TContext
> => {
  const mutationKey = ['printingControllerGenerateIdCards'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerGenerateIdCards>>,
    { data: IdCardFilterDto }
  > = (props) => {
    const { data } = props ?? {};

    return printingControllerGenerateIdCards(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerGenerateIdCardsMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerGenerateIdCards>>
>;
export type PrintingControllerGenerateIdCardsMutationBody = IdCardFilterDto;
export type PrintingControllerGenerateIdCardsMutationError = unknown;

export const usePrintingControllerGenerateIdCards = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerGenerateIdCards>>,
      TError,
      { data: IdCardFilterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerGenerateIdCards>>,
  TError,
  { data: IdCardFilterDto },
  TContext
> => {
  const mutationOptions = getPrintingControllerGenerateIdCardsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const printingControllerPreviewSittingSlips = (
  params: PrintingControllerPreviewSittingSlipsParams,
  signal?: AbortSignal,
) => {
  return service<SittingSlipPreviewResponseDto>({
    url: `/printing/sitting-slips/preview`,
    method: 'GET',
    params,
    signal,
  });
};

export const getPrintingControllerPreviewSittingSlipsQueryKey = (
  params?: PrintingControllerPreviewSittingSlipsParams,
) => {
  return [`/printing/sitting-slips/preview`, ...(params ? [params] : [])] as const;
};

export const getPrintingControllerPreviewSittingSlipsQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewSittingSlipsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerPreviewSittingSlipsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>> = ({ signal }) =>
    printingControllerPreviewSittingSlips(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerPreviewSittingSlipsQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>
>;
export type PrintingControllerPreviewSittingSlipsQueryError = unknown;

export function usePrintingControllerPreviewSittingSlips<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewSittingSlipsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewSittingSlips<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewSittingSlipsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewSittingSlips<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewSittingSlipsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerPreviewSittingSlips<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewSittingSlipsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlips>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerPreviewSittingSlipsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerPreviewSittingSlipDesign = (signal?: AbortSignal) => {
  return service<void>({ url: `/printing/sitting-slips/preview-design`, method: 'GET', signal });
};

export const getPrintingControllerPreviewSittingSlipDesignQueryKey = () => {
  return [`/printing/sitting-slips/preview-design`] as const;
};

export const getPrintingControllerPreviewSittingSlipDesignQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerPreviewSittingSlipDesignQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>> = ({ signal }) =>
    printingControllerPreviewSittingSlipDesign(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerPreviewSittingSlipDesignQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>
>;
export type PrintingControllerPreviewSittingSlipDesignQueryError = unknown;

export function usePrintingControllerPreviewSittingSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewSittingSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewSittingSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerPreviewSittingSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewSittingSlipDesign>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerPreviewSittingSlipDesignQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerGenerateSittingSlips = (
  sittingSlipFilterDto: SittingSlipFilterDto,
  signal?: AbortSignal,
) => {
  return service<void>({
    url: `/printing/sitting-slips/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sittingSlipFilterDto,
    signal,
  });
};

export const getPrintingControllerGenerateSittingSlipsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerGenerateSittingSlips>>,
    TError,
    { data: SittingSlipFilterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerGenerateSittingSlips>>,
  TError,
  { data: SittingSlipFilterDto },
  TContext
> => {
  const mutationKey = ['printingControllerGenerateSittingSlips'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerGenerateSittingSlips>>,
    { data: SittingSlipFilterDto }
  > = (props) => {
    const { data } = props ?? {};

    return printingControllerGenerateSittingSlips(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerGenerateSittingSlipsMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerGenerateSittingSlips>>
>;
export type PrintingControllerGenerateSittingSlipsMutationBody = SittingSlipFilterDto;
export type PrintingControllerGenerateSittingSlipsMutationError = unknown;

export const usePrintingControllerGenerateSittingSlips = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerGenerateSittingSlips>>,
      TError,
      { data: SittingSlipFilterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerGenerateSittingSlips>>,
  TError,
  { data: SittingSlipFilterDto },
  TContext
> => {
  const mutationOptions = getPrintingControllerGenerateSittingSlipsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const printingControllerPreviewAttendanceSheets = (
  params: PrintingControllerPreviewAttendanceSheetsParams,
  signal?: AbortSignal,
) => {
  return service<AttendanceSheetPreviewResponseDto>({
    url: `/printing/attendance-sheets/preview`,
    method: 'GET',
    params,
    signal,
  });
};

export const getPrintingControllerPreviewAttendanceSheetsQueryKey = (
  params?: PrintingControllerPreviewAttendanceSheetsParams,
) => {
  return [`/printing/attendance-sheets/preview`, ...(params ? [params] : [])] as const;
};

export const getPrintingControllerPreviewAttendanceSheetsQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewAttendanceSheetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerPreviewAttendanceSheetsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>> = ({ signal }) =>
    printingControllerPreviewAttendanceSheets(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerPreviewAttendanceSheetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>
>;
export type PrintingControllerPreviewAttendanceSheetsQueryError = unknown;

export function usePrintingControllerPreviewAttendanceSheets<
  TData = Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewAttendanceSheetsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewAttendanceSheets<
  TData = Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewAttendanceSheetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewAttendanceSheets<
  TData = Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewAttendanceSheetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerPreviewAttendanceSheets<
  TData = Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>,
  TError = unknown,
>(
  params: PrintingControllerPreviewAttendanceSheetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewAttendanceSheets>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerPreviewAttendanceSheetsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerGenerateAttendanceSheets = (
  attendanceSheetFilterDto: AttendanceSheetFilterDto,
  signal?: AbortSignal,
) => {
  return service<void>({
    url: `/printing/attendance-sheets/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: attendanceSheetFilterDto,
    signal,
  });
};

export const getPrintingControllerGenerateAttendanceSheetsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerGenerateAttendanceSheets>>,
    TError,
    { data: AttendanceSheetFilterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerGenerateAttendanceSheets>>,
  TError,
  { data: AttendanceSheetFilterDto },
  TContext
> => {
  const mutationKey = ['printingControllerGenerateAttendanceSheets'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerGenerateAttendanceSheets>>,
    { data: AttendanceSheetFilterDto }
  > = (props) => {
    const { data } = props ?? {};

    return printingControllerGenerateAttendanceSheets(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerGenerateAttendanceSheetsMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerGenerateAttendanceSheets>>
>;
export type PrintingControllerGenerateAttendanceSheetsMutationBody = AttendanceSheetFilterDto;
export type PrintingControllerGenerateAttendanceSheetsMutationError = unknown;

export const usePrintingControllerGenerateAttendanceSheets = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerGenerateAttendanceSheets>>,
      TError,
      { data: AttendanceSheetFilterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerGenerateAttendanceSheets>>,
  TError,
  { data: AttendanceSheetFilterDto },
  TContext
> => {
  const mutationOptions = getPrintingControllerGenerateAttendanceSheetsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const printingControllerPreviewVerificationSlips = (
  verificationSlipFilterDto: VerificationSlipFilterDto,
  signal?: AbortSignal,
) => {
  return service<VerificationSlipPreviewResponseDto>({
    url: `/printing/verification-slips/preview`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: verificationSlipFilterDto,
    signal,
  });
};

export const getPrintingControllerPreviewVerificationSlipsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerPreviewVerificationSlips>>,
    TError,
    { data: VerificationSlipFilterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerPreviewVerificationSlips>>,
  TError,
  { data: VerificationSlipFilterDto },
  TContext
> => {
  const mutationKey = ['printingControllerPreviewVerificationSlips'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerPreviewVerificationSlips>>,
    { data: VerificationSlipFilterDto }
  > = (props) => {
    const { data } = props ?? {};

    return printingControllerPreviewVerificationSlips(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerPreviewVerificationSlipsMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerPreviewVerificationSlips>>
>;
export type PrintingControllerPreviewVerificationSlipsMutationBody = VerificationSlipFilterDto;
export type PrintingControllerPreviewVerificationSlipsMutationError = unknown;

export const usePrintingControllerPreviewVerificationSlips = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerPreviewVerificationSlips>>,
      TError,
      { data: VerificationSlipFilterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerPreviewVerificationSlips>>,
  TError,
  { data: VerificationSlipFilterDto },
  TContext
> => {
  const mutationOptions = getPrintingControllerPreviewVerificationSlipsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const printingControllerPreviewVerificationSlipDesign = (signal?: AbortSignal) => {
  return service<void>({ url: `/printing/verification-slips/preview-design`, method: 'GET', signal });
};

export const getPrintingControllerPreviewVerificationSlipDesignQueryKey = () => {
  return [`/printing/verification-slips/preview-design`] as const;
};

export const getPrintingControllerPreviewVerificationSlipDesignQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerPreviewVerificationSlipDesignQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>> = ({
    signal,
  }) => printingControllerPreviewVerificationSlipDesign(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerPreviewVerificationSlipDesignQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>
>;
export type PrintingControllerPreviewVerificationSlipDesignQueryError = unknown;

export function usePrintingControllerPreviewVerificationSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewVerificationSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
          TError,
          Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerPreviewVerificationSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerPreviewVerificationSlipDesign<
  TData = Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerPreviewVerificationSlipDesign>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerPreviewVerificationSlipDesignQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerGenerateVerificationSlips = (
  verificationSlipFilterDto: VerificationSlipFilterDto,
  signal?: AbortSignal,
) => {
  return service<void>({
    url: `/printing/verification-slips/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: verificationSlipFilterDto,
    signal,
  });
};

export const getPrintingControllerGenerateVerificationSlipsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerGenerateVerificationSlips>>,
    TError,
    { data: VerificationSlipFilterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerGenerateVerificationSlips>>,
  TError,
  { data: VerificationSlipFilterDto },
  TContext
> => {
  const mutationKey = ['printingControllerGenerateVerificationSlips'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerGenerateVerificationSlips>>,
    { data: VerificationSlipFilterDto }
  > = (props) => {
    const { data } = props ?? {};

    return printingControllerGenerateVerificationSlips(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerGenerateVerificationSlipsMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerGenerateVerificationSlips>>
>;
export type PrintingControllerGenerateVerificationSlipsMutationBody = VerificationSlipFilterDto;
export type PrintingControllerGenerateVerificationSlipsMutationError = unknown;

export const usePrintingControllerGenerateVerificationSlips = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerGenerateVerificationSlips>>,
      TError,
      { data: VerificationSlipFilterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerGenerateVerificationSlips>>,
  TError,
  { data: VerificationSlipFilterDto },
  TContext
> => {
  const mutationOptions = getPrintingControllerGenerateVerificationSlipsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const printingControllerListCardPrintRequests = (
  params: PrintingControllerListCardPrintRequestsParams,
  signal?: AbortSignal,
) => {
  return service<ListCardPrintRequestsResponseDto>({ url: `/printing/card-requests`, method: 'GET', params, signal });
};

export const getPrintingControllerListCardPrintRequestsQueryKey = (
  params?: PrintingControllerListCardPrintRequestsParams,
) => {
  return [`/printing/card-requests`, ...(params ? [params] : [])] as const;
};

export const getPrintingControllerListCardPrintRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerListCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerListCardPrintRequestsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>> = ({ signal }) =>
    printingControllerListCardPrintRequests(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerListCardPrintRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>
>;
export type PrintingControllerListCardPrintRequestsQueryError = unknown;

export function usePrintingControllerListCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerListCardPrintRequestsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
          TError,
          Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerListCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerListCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
          TError,
          Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerListCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerListCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerListCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerListCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerListCardPrintRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerListCardPrintRequestsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerCountCardPrintRequests = (
  params: PrintingControllerCountCardPrintRequestsParams,
  signal?: AbortSignal,
) => {
  return service<CountCardPrintRequestsResponseDto>({
    url: `/printing/card-requests/count`,
    method: 'GET',
    params,
    signal,
  });
};

export const getPrintingControllerCountCardPrintRequestsQueryKey = (
  params?: PrintingControllerCountCardPrintRequestsParams,
) => {
  return [`/printing/card-requests/count`, ...(params ? [params] : [])] as const;
};

export const getPrintingControllerCountCardPrintRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerCountCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintingControllerCountCardPrintRequestsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>> = ({ signal }) =>
    printingControllerCountCardPrintRequests(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrintingControllerCountCardPrintRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>
>;
export type PrintingControllerCountCardPrintRequestsQueryError = unknown;

export function usePrintingControllerCountCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerCountCardPrintRequestsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
          TError,
          Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerCountCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerCountCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
          TError,
          Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrintingControllerCountCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerCountCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrintingControllerCountCardPrintRequests<
  TData = Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>,
  TError = unknown,
>(
  params: PrintingControllerCountCardPrintRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof printingControllerCountCardPrintRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintingControllerCountCardPrintRequestsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const printingControllerProcessCardPrintRequests = (
  processCardPrintRequestsDto: ProcessCardPrintRequestsDto,
  signal?: AbortSignal,
) => {
  return service<ProcessCardPrintRequestsResponseDto>({
    url: `/printing/card-requests/process`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: processCardPrintRequestsDto,
    signal,
  });
};

export const getPrintingControllerProcessCardPrintRequestsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerProcessCardPrintRequests>>,
    TError,
    { data: ProcessCardPrintRequestsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerProcessCardPrintRequests>>,
  TError,
  { data: ProcessCardPrintRequestsDto },
  TContext
> => {
  const mutationKey = ['printingControllerProcessCardPrintRequests'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerProcessCardPrintRequests>>,
    { data: ProcessCardPrintRequestsDto }
  > = (props) => {
    const { data } = props ?? {};

    return printingControllerProcessCardPrintRequests(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerProcessCardPrintRequestsMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerProcessCardPrintRequests>>
>;
export type PrintingControllerProcessCardPrintRequestsMutationBody = ProcessCardPrintRequestsDto;
export type PrintingControllerProcessCardPrintRequestsMutationError = unknown;

export const usePrintingControllerProcessCardPrintRequests = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerProcessCardPrintRequests>>,
      TError,
      { data: ProcessCardPrintRequestsDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerProcessCardPrintRequests>>,
  TError,
  { data: ProcessCardPrintRequestsDto },
  TContext
> => {
  const mutationOptions = getPrintingControllerProcessCardPrintRequestsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const printingControllerCreateCardPrintRequests = (
  createCardPrintRequestDto: CreateCardPrintRequestDto,
  signal?: AbortSignal,
) => {
  return service<CreateCardPrintRequestResponseDto>({
    url: `/printing/card-requests/manual`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createCardPrintRequestDto,
    signal,
  });
};

export const getPrintingControllerCreateCardPrintRequestsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerCreateCardPrintRequests>>,
    TError,
    { data: CreateCardPrintRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerCreateCardPrintRequests>>,
  TError,
  { data: CreateCardPrintRequestDto },
  TContext
> => {
  const mutationKey = ['printingControllerCreateCardPrintRequests'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerCreateCardPrintRequests>>,
    { data: CreateCardPrintRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return printingControllerCreateCardPrintRequests(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerCreateCardPrintRequestsMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerCreateCardPrintRequests>>
>;
export type PrintingControllerCreateCardPrintRequestsMutationBody = CreateCardPrintRequestDto;
export type PrintingControllerCreateCardPrintRequestsMutationError = unknown;

export const usePrintingControllerCreateCardPrintRequests = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerCreateCardPrintRequests>>,
      TError,
      { data: CreateCardPrintRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerCreateCardPrintRequests>>,
  TError,
  { data: CreateCardPrintRequestDto },
  TContext
> => {
  const mutationOptions = getPrintingControllerCreateCardPrintRequestsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const printingControllerCancelCardPrintRequest = (id: string) => {
  return service<CancelCardPrintRequestResponseDto>({ url: `/printing/card-requests/${id}/cancel`, method: 'PATCH' });
};

export const getPrintingControllerCancelCardPrintRequestMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof printingControllerCancelCardPrintRequest>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof printingControllerCancelCardPrintRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['printingControllerCancelCardPrintRequest'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof printingControllerCancelCardPrintRequest>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return printingControllerCancelCardPrintRequest(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintingControllerCancelCardPrintRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof printingControllerCancelCardPrintRequest>>
>;

export type PrintingControllerCancelCardPrintRequestMutationError = unknown;

export const usePrintingControllerCancelCardPrintRequest = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof printingControllerCancelCardPrintRequest>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof printingControllerCancelCardPrintRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPrintingControllerCancelCardPrintRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
