/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  CreateQuestionSetDto,
  CreateQuestionSetResponseDto,
  DetailQuestionSetsResponseDto,
  ListQuestionSetsResponseDto,
  QuestionSetControllerFindAllParams,
  QuestionSetControllerFindOneParams,
  UpdateQuestionSetDto,
  UpdateQuestionSetResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const questionSetControllerCreate = (createQuestionSetDto: CreateQuestionSetDto, signal?: AbortSignal) => {
  return service<CreateQuestionSetResponseDto>({
    url: `/question-set`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createQuestionSetDto,
    signal,
  });
};

export const getQuestionSetControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionSetControllerCreate>>,
    TError,
    { data: CreateQuestionSetDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionSetControllerCreate>>,
  TError,
  { data: CreateQuestionSetDto },
  TContext
> => {
  const mutationKey = ['questionSetControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof questionSetControllerCreate>>,
    { data: CreateQuestionSetDto }
  > = (props) => {
    const { data } = props ?? {};

    return questionSetControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionSetControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionSetControllerCreate>>
>;
export type QuestionSetControllerCreateMutationBody = CreateQuestionSetDto;
export type QuestionSetControllerCreateMutationError = unknown;

export const useQuestionSetControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionSetControllerCreate>>,
      TError,
      { data: CreateQuestionSetDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof questionSetControllerCreate>>,
  TError,
  { data: CreateQuestionSetDto },
  TContext
> => {
  const mutationOptions = getQuestionSetControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionSetControllerFindAll = (params?: QuestionSetControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListQuestionSetsResponseDto>({ url: `/question-set`, method: 'GET', params, signal });
};

export const getQuestionSetControllerFindAllQueryKey = (params?: QuestionSetControllerFindAllParams) => {
  return [`/question-set`, ...(params ? [params] : [])] as const;
};

export const getQuestionSetControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof questionSetControllerFindAll>>,
  TError = unknown,
>(
  params?: QuestionSetControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindAll>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQuestionSetControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof questionSetControllerFindAll>>> = ({ signal }) =>
    questionSetControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof questionSetControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QuestionSetControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof questionSetControllerFindAll>>
>;
export type QuestionSetControllerFindAllQueryError = unknown;

export function useQuestionSetControllerFindAll<
  TData = Awaited<ReturnType<typeof questionSetControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | QuestionSetControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionSetControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof questionSetControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionSetControllerFindAll<
  TData = Awaited<ReturnType<typeof questionSetControllerFindAll>>,
  TError = unknown,
>(
  params?: QuestionSetControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionSetControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof questionSetControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionSetControllerFindAll<
  TData = Awaited<ReturnType<typeof questionSetControllerFindAll>>,
  TError = unknown,
>(
  params?: QuestionSetControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useQuestionSetControllerFindAll<
  TData = Awaited<ReturnType<typeof questionSetControllerFindAll>>,
  TError = unknown,
>(
  params?: QuestionSetControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQuestionSetControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const questionSetControllerFindOne = (
  id: string,
  params?: QuestionSetControllerFindOneParams,
  signal?: AbortSignal,
) => {
  return service<DetailQuestionSetsResponseDto>({ url: `/question-set/${id}`, method: 'GET', params, signal });
};

export const getQuestionSetControllerFindOneQueryKey = (id?: string, params?: QuestionSetControllerFindOneParams) => {
  return [`/question-set/${id}`, ...(params ? [params] : [])] as const;
};

export const getQuestionSetControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof questionSetControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: QuestionSetControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindOne>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQuestionSetControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof questionSetControllerFindOne>>> = ({ signal }) =>
    questionSetControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof questionSetControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QuestionSetControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof questionSetControllerFindOne>>
>;
export type QuestionSetControllerFindOneQueryError = unknown;

export function useQuestionSetControllerFindOne<
  TData = Awaited<ReturnType<typeof questionSetControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params: undefined | QuestionSetControllerFindOneParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionSetControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof questionSetControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionSetControllerFindOne<
  TData = Awaited<ReturnType<typeof questionSetControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: QuestionSetControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionSetControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof questionSetControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionSetControllerFindOne<
  TData = Awaited<ReturnType<typeof questionSetControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: QuestionSetControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useQuestionSetControllerFindOne<
  TData = Awaited<ReturnType<typeof questionSetControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: QuestionSetControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof questionSetControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQuestionSetControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const questionSetControllerUpdate = (id: string, updateQuestionSetDto: UpdateQuestionSetDto) => {
  return service<UpdateQuestionSetResponseDto>({
    url: `/question-set/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateQuestionSetDto,
  });
};

export const getQuestionSetControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionSetControllerUpdate>>,
    TError,
    { id: string; data: UpdateQuestionSetDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionSetControllerUpdate>>,
  TError,
  { id: string; data: UpdateQuestionSetDto },
  TContext
> => {
  const mutationKey = ['questionSetControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof questionSetControllerUpdate>>,
    { id: string; data: UpdateQuestionSetDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return questionSetControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionSetControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionSetControllerUpdate>>
>;
export type QuestionSetControllerUpdateMutationBody = UpdateQuestionSetDto;
export type QuestionSetControllerUpdateMutationError = unknown;

export const useQuestionSetControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionSetControllerUpdate>>,
      TError,
      { id: string; data: UpdateQuestionSetDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof questionSetControllerUpdate>>,
  TError,
  { id: string; data: UpdateQuestionSetDto },
  TContext
> => {
  const mutationOptions = getQuestionSetControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionSetControllerRemove = (id: string) => {
  return service<ActionResponseDto>({ url: `/question-set/${id}`, method: 'DELETE' });
};

export const getQuestionSetControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionSetControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof questionSetControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['questionSetControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof questionSetControllerRemove>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return questionSetControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionSetControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionSetControllerRemove>>
>;

export type QuestionSetControllerRemoveMutationError = unknown;

export const useQuestionSetControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionSetControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof questionSetControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getQuestionSetControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionSetControllerDeactivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/question-set/${id}/deactivate`, method: 'DELETE' });
};

export const getQuestionSetControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionSetControllerDeactivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionSetControllerDeactivate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['questionSetControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof questionSetControllerDeactivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return questionSetControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionSetControllerDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionSetControllerDeactivate>>
>;

export type QuestionSetControllerDeactivateMutationError = unknown;

export const useQuestionSetControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionSetControllerDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof questionSetControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getQuestionSetControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionSetControllerActivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/question-set/${id}/activate`, method: 'PATCH' });
};

export const getQuestionSetControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionSetControllerActivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof questionSetControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['questionSetControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof questionSetControllerActivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return questionSetControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionSetControllerActivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionSetControllerActivate>>
>;

export type QuestionSetControllerActivateMutationError = unknown;

export const useQuestionSetControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionSetControllerActivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof questionSetControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getQuestionSetControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
