/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * App Service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateInteractionDto,
  CreateInteractionResponseDto,
  GetInteractionTemplateResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const interactionsControllerGetTemplate = (studentId: string, signal?: AbortSignal) => {
  return service<GetInteractionTemplateResponseDto>({
    url: `/interactions/template/${studentId}`,
    method: 'GET',
    signal,
  });
};

export const getInteractionsControllerGetTemplateQueryKey = (studentId?: string) => {
  return [`/interactions/template/${studentId}`] as const;
};

export const getInteractionsControllerGetTemplateQueryOptions = <
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  studentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInteractionsControllerGetTemplateQueryKey(studentId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>> = ({ signal }) =>
    interactionsControllerGetTemplate(studentId, signal);

  return { queryKey, queryFn, enabled: !!studentId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InteractionsControllerGetTemplateQueryResult = NonNullable<
  Awaited<ReturnType<typeof interactionsControllerGetTemplate>>
>;
export type InteractionsControllerGetTemplateQueryError = unknown;

export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  studentId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  studentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  studentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  studentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInteractionsControllerGetTemplateQueryOptions(studentId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const interactionsControllerCreate = (createInteractionDto: CreateInteractionDto, signal?: AbortSignal) => {
  return service<CreateInteractionResponseDto>({
    url: `/interactions`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createInteractionDto,
    signal,
  });
};

export const getInteractionsControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof interactionsControllerCreate>>,
    TError,
    { data: CreateInteractionDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof interactionsControllerCreate>>,
  TError,
  { data: CreateInteractionDto },
  TContext
> => {
  const mutationKey = ['interactionsControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof interactionsControllerCreate>>,
    { data: CreateInteractionDto }
  > = (props) => {
    const { data } = props ?? {};

    return interactionsControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InteractionsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof interactionsControllerCreate>>
>;
export type InteractionsControllerCreateMutationBody = CreateInteractionDto;
export type InteractionsControllerCreateMutationError = unknown;

export const useInteractionsControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof interactionsControllerCreate>>,
      TError,
      { data: CreateInteractionDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof interactionsControllerCreate>>,
  TError,
  { data: CreateInteractionDto },
  TContext
> => {
  const mutationOptions = getInteractionsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
