/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * App Service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateInteractionDto,
  CreateInteractionResponseDto,
  GetInteractionTemplateResponseDto,
  InteractionsControllerFindAllParams,
  InteractionsControllerGetDashboardParams,
  InteractionsDashboardResponseDto,
  ListInteractionsResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const interactionsControllerFindAll = (params?: InteractionsControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListInteractionsResponseDto>({ url: `/interactions`, method: 'GET', params, signal });
};

export const getInteractionsControllerFindAllQueryKey = (params?: InteractionsControllerFindAllParams) => {
  return [`/interactions`, ...(params ? [params] : [])] as const;
};

export const getInteractionsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof interactionsControllerFindAll>>,
  TError = unknown,
>(
  params?: InteractionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerFindAll>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInteractionsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof interactionsControllerFindAll>>> = ({ signal }) =>
    interactionsControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof interactionsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InteractionsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof interactionsControllerFindAll>>
>;
export type InteractionsControllerFindAllQueryError = unknown;

export function useInteractionsControllerFindAll<
  TData = Awaited<ReturnType<typeof interactionsControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | InteractionsControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerFindAll<
  TData = Awaited<ReturnType<typeof interactionsControllerFindAll>>,
  TError = unknown,
>(
  params?: InteractionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerFindAll<
  TData = Awaited<ReturnType<typeof interactionsControllerFindAll>>,
  TError = unknown,
>(
  params?: InteractionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInteractionsControllerFindAll<
  TData = Awaited<ReturnType<typeof interactionsControllerFindAll>>,
  TError = unknown,
>(
  params?: InteractionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInteractionsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const interactionsControllerCreate = (createInteractionDto: CreateInteractionDto, signal?: AbortSignal) => {
  return service<CreateInteractionResponseDto>({
    url: `/interactions`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createInteractionDto,
    signal,
  });
};

export const getInteractionsControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof interactionsControllerCreate>>,
    TError,
    { data: CreateInteractionDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof interactionsControllerCreate>>,
  TError,
  { data: CreateInteractionDto },
  TContext
> => {
  const mutationKey = ['interactionsControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof interactionsControllerCreate>>,
    { data: CreateInteractionDto }
  > = (props) => {
    const { data } = props ?? {};

    return interactionsControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InteractionsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof interactionsControllerCreate>>
>;
export type InteractionsControllerCreateMutationBody = CreateInteractionDto;
export type InteractionsControllerCreateMutationError = unknown;

export const useInteractionsControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof interactionsControllerCreate>>,
      TError,
      { data: CreateInteractionDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof interactionsControllerCreate>>,
  TError,
  { data: CreateInteractionDto },
  TContext
> => {
  const mutationOptions = getInteractionsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const interactionsControllerGetDashboard = (
  params: InteractionsControllerGetDashboardParams,
  signal?: AbortSignal,
) => {
  return service<InteractionsDashboardResponseDto>({ url: `/interactions/dashboard`, method: 'GET', params, signal });
};

export const getInteractionsControllerGetDashboardQueryKey = (params?: InteractionsControllerGetDashboardParams) => {
  return [`/interactions/dashboard`, ...(params ? [params] : [])] as const;
};

export const getInteractionsControllerGetDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
  TError = unknown,
>(
  params: InteractionsControllerGetDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetDashboard>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInteractionsControllerGetDashboardQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof interactionsControllerGetDashboard>>> = ({ signal }) =>
    interactionsControllerGetDashboard(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InteractionsControllerGetDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof interactionsControllerGetDashboard>>
>;
export type InteractionsControllerGetDashboardQueryError = unknown;

export function useInteractionsControllerGetDashboard<
  TData = Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
  TError = unknown,
>(
  params: InteractionsControllerGetDashboardParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetDashboard>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerGetDashboard>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerGetDashboard<
  TData = Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
  TError = unknown,
>(
  params: InteractionsControllerGetDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetDashboard>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerGetDashboard>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerGetDashboard<
  TData = Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
  TError = unknown,
>(
  params: InteractionsControllerGetDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetDashboard>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInteractionsControllerGetDashboard<
  TData = Awaited<ReturnType<typeof interactionsControllerGetDashboard>>,
  TError = unknown,
>(
  params: InteractionsControllerGetDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetDashboard>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInteractionsControllerGetDashboardQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const interactionsControllerGetTemplate = (admissionId: string, signal?: AbortSignal) => {
  return service<GetInteractionTemplateResponseDto>({
    url: `/interactions/template/${admissionId}`,
    method: 'GET',
    signal,
  });
};

export const getInteractionsControllerGetTemplateQueryKey = (admissionId?: string) => {
  return [`/interactions/template/${admissionId}`] as const;
};

export const getInteractionsControllerGetTemplateQueryOptions = <
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  admissionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInteractionsControllerGetTemplateQueryKey(admissionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>> = ({ signal }) =>
    interactionsControllerGetTemplate(admissionId, signal);

  return { queryKey, queryFn, enabled: !!admissionId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InteractionsControllerGetTemplateQueryResult = NonNullable<
  Awaited<ReturnType<typeof interactionsControllerGetTemplate>>
>;
export type InteractionsControllerGetTemplateQueryError = unknown;

export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  admissionId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  admissionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
          TError,
          Awaited<ReturnType<typeof interactionsControllerGetTemplate>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  admissionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInteractionsControllerGetTemplate<
  TData = Awaited<ReturnType<typeof interactionsControllerGetTemplate>>,
  TError = unknown,
>(
  admissionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof interactionsControllerGetTemplate>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInteractionsControllerGetTemplateQueryOptions(admissionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
