/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  AdminUsersControllerFindAllParams,
  CreateAdminUserDto,
  CreateAdminUserResponseDto,
  DetailAdminUserResponseDto,
  ListAdminUsersResponseDto,
  UpdateAdminUserDto,
  UpdateAdminUserResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const adminUsersControllerCreate = (createAdminUserDto: CreateAdminUserDto, signal?: AbortSignal) => {
  return service<CreateAdminUserResponseDto>({
    url: `/admin/users`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createAdminUserDto,
    signal,
  });
};

export const getAdminUsersControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersControllerCreate>>,
    TError,
    { data: CreateAdminUserDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersControllerCreate>>,
  TError,
  { data: CreateAdminUserDto },
  TContext
> => {
  const mutationKey = ['adminUsersControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersControllerCreate>>,
    { data: CreateAdminUserDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminUsersControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUsersControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersControllerCreate>>
>;
export type AdminUsersControllerCreateMutationBody = CreateAdminUserDto;
export type AdminUsersControllerCreateMutationError = unknown;

export const useAdminUsersControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersControllerCreate>>,
      TError,
      { data: CreateAdminUserDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminUsersControllerCreate>>,
  TError,
  { data: CreateAdminUserDto },
  TContext
> => {
  const mutationOptions = getAdminUsersControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminUsersControllerFindAll = (params?: AdminUsersControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListAdminUsersResponseDto>({ url: `/admin/users`, method: 'GET', params, signal });
};

export const getAdminUsersControllerFindAllQueryKey = (params?: AdminUsersControllerFindAllParams) => {
  return [`/admin/users`, ...(params ? [params] : [])] as const;
};

export const getAdminUsersControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
  TError = unknown,
>(
  params?: AdminUsersControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindAll>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminUsersControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminUsersControllerFindAll>>> = ({ signal }) =>
    adminUsersControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminUsersControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersControllerFindAll>>
>;
export type AdminUsersControllerFindAllQueryError = unknown;

export function useAdminUsersControllerFindAll<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | AdminUsersControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof adminUsersControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminUsersControllerFindAll<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
  TError = unknown,
>(
  params?: AdminUsersControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof adminUsersControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminUsersControllerFindAll<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
  TError = unknown,
>(
  params?: AdminUsersControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAdminUsersControllerFindAll<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindAll>>,
  TError = unknown,
>(
  params?: AdminUsersControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminUsersControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const adminUsersControllerFindOne = (id: string, signal?: AbortSignal) => {
  return service<DetailAdminUserResponseDto>({ url: `/admin/users/${id}`, method: 'GET', signal });
};

export const getAdminUsersControllerFindOneQueryKey = (id?: string) => {
  return [`/admin/users/${id}`] as const;
};

export const getAdminUsersControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindOne>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminUsersControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminUsersControllerFindOne>>> = ({ signal }) =>
    adminUsersControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminUsersControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersControllerFindOne>>
>;
export type AdminUsersControllerFindOneQueryError = unknown;

export function useAdminUsersControllerFindOne<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof adminUsersControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminUsersControllerFindOne<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof adminUsersControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminUsersControllerFindOne<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAdminUsersControllerFindOne<
  TData = Awaited<ReturnType<typeof adminUsersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminUsersControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminUsersControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const adminUsersControllerUpdate = (id: string, updateAdminUserDto: UpdateAdminUserDto) => {
  return service<UpdateAdminUserResponseDto>({
    url: `/admin/users/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateAdminUserDto,
  });
};

export const getAdminUsersControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersControllerUpdate>>,
    TError,
    { id: string; data: UpdateAdminUserDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersControllerUpdate>>,
  TError,
  { id: string; data: UpdateAdminUserDto },
  TContext
> => {
  const mutationKey = ['adminUsersControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUsersControllerUpdate>>,
    { id: string; data: UpdateAdminUserDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return adminUsersControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUsersControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersControllerUpdate>>
>;
export type AdminUsersControllerUpdateMutationBody = UpdateAdminUserDto;
export type AdminUsersControllerUpdateMutationError = unknown;

export const useAdminUsersControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersControllerUpdate>>,
      TError,
      { id: string; data: UpdateAdminUserDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminUsersControllerUpdate>>,
  TError,
  { id: string; data: UpdateAdminUserDto },
  TContext
> => {
  const mutationOptions = getAdminUsersControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminUsersControllerDeactivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/admin/users/${id}`, method: 'DELETE' });
};

export const getAdminUsersControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersControllerDeactivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUsersControllerDeactivate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['adminUsersControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUsersControllerDeactivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return adminUsersControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUsersControllerDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersControllerDeactivate>>
>;

export type AdminUsersControllerDeactivateMutationError = unknown;

export const useAdminUsersControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersControllerDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof adminUsersControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAdminUsersControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminUsersControllerActivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/admin/users/${id}/activate`, method: 'PUT' });
};

export const getAdminUsersControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersControllerActivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof adminUsersControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['adminUsersControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUsersControllerActivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return adminUsersControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUsersControllerActivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersControllerActivate>>
>;

export type AdminUsersControllerActivateMutationError = unknown;

export const useAdminUsersControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersControllerActivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof adminUsersControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAdminUsersControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminUsersControllerReinvite = (id: string, signal?: AbortSignal) => {
  return service<ActionResponseDto>({ url: `/admin/users/${id}/reinvite`, method: 'POST', signal });
};

export const getAdminUsersControllerReinviteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUsersControllerReinvite>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof adminUsersControllerReinvite>>, TError, { id: string }, TContext> => {
  const mutationKey = ['adminUsersControllerReinvite'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUsersControllerReinvite>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return adminUsersControllerReinvite(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUsersControllerReinviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUsersControllerReinvite>>
>;

export type AdminUsersControllerReinviteMutationError = unknown;

export const useAdminUsersControllerReinvite = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUsersControllerReinvite>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof adminUsersControllerReinvite>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAdminUsersControllerReinviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
