/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * App Service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  CreateSessionDto,
  CreateSessionResponseDto,
  DetailSessionsResponseDto,
  ListSessionsResponseDto,
  SessionControllerFindAllParams,
  SessionControllerFindOneParams,
  UpdateSessionDto,
  UpdateSessionResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const sessionControllerCreate = (createSessionDto: CreateSessionDto, signal?: AbortSignal) => {
  return service<CreateSessionResponseDto>({
    url: `/session`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createSessionDto,
    signal,
  });
};

export const getSessionControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerCreate>>,
    TError,
    { data: CreateSessionDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerCreate>>,
  TError,
  { data: CreateSessionDto },
  TContext
> => {
  const mutationKey = ['sessionControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerCreate>>,
    { data: CreateSessionDto }
  > = (props) => {
    const { data } = props ?? {};

    return sessionControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof sessionControllerCreate>>>;
export type SessionControllerCreateMutationBody = CreateSessionDto;
export type SessionControllerCreateMutationError = unknown;

export const useSessionControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerCreate>>,
      TError,
      { data: CreateSessionDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerCreate>>,
  TError,
  { data: CreateSessionDto },
  TContext
> => {
  const mutationOptions = getSessionControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const sessionControllerFindAll = (params?: SessionControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListSessionsResponseDto>({ url: `/session`, method: 'GET', params, signal });
};

export const getSessionControllerFindAllQueryKey = (params?: SessionControllerFindAllParams) => {
  return [`/session`, ...(params ? [params] : [])] as const;
};

export const getSessionControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = unknown,
>(
  params?: SessionControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSessionControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionControllerFindAll>>> = ({ signal }) =>
    sessionControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof sessionControllerFindAll>>>;
export type SessionControllerFindAllQueryError = unknown;

export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | SessionControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = unknown,
>(
  params?: SessionControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = unknown,
>(
  params?: SessionControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSessionControllerFindAll<
  TData = Awaited<ReturnType<typeof sessionControllerFindAll>>,
  TError = unknown,
>(
  params?: SessionControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSessionControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const sessionControllerFindOne = (id: string, params?: SessionControllerFindOneParams, signal?: AbortSignal) => {
  return service<DetailSessionsResponseDto>({ url: `/session/${id}`, method: 'GET', params, signal });
};

export const getSessionControllerFindOneQueryKey = (id?: string, params?: SessionControllerFindOneParams) => {
  return [`/session/${id}`, ...(params ? [params] : [])] as const;
};

export const getSessionControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: SessionControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSessionControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionControllerFindOne>>> = ({ signal }) =>
    sessionControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof sessionControllerFindOne>>>;
export type SessionControllerFindOneQueryError = unknown;

export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params: undefined | SessionControllerFindOneParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: SessionControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: SessionControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSessionControllerFindOne<
  TData = Awaited<ReturnType<typeof sessionControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: SessionControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSessionControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const sessionControllerUpdate = (id: string, updateSessionDto: UpdateSessionDto) => {
  return service<UpdateSessionResponseDto>({
    url: `/session/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateSessionDto,
  });
};

export const getSessionControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerUpdate>>,
    TError,
    { id: string; data: UpdateSessionDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerUpdate>>,
  TError,
  { id: string; data: UpdateSessionDto },
  TContext
> => {
  const mutationKey = ['sessionControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerUpdate>>,
    { id: string; data: UpdateSessionDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return sessionControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof sessionControllerUpdate>>>;
export type SessionControllerUpdateMutationBody = UpdateSessionDto;
export type SessionControllerUpdateMutationError = unknown;

export const useSessionControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerUpdate>>,
      TError,
      { id: string; data: UpdateSessionDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerUpdate>>,
  TError,
  { id: string; data: UpdateSessionDto },
  TContext
> => {
  const mutationOptions = getSessionControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const sessionControllerRemove = (id: string) => {
  return service<ActionResponseDto>({ url: `/session/${id}`, method: 'DELETE' });
};

export const getSessionControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof sessionControllerRemove>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof sessionControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['sessionControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionControllerRemove>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return sessionControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof sessionControllerRemove>>>;

export type SessionControllerRemoveMutationError = unknown;

export const useSessionControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof sessionControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getSessionControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const sessionControllerDeactivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/session/${id}/deactivate`, method: 'DELETE' });
};

export const getSessionControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerDeactivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof sessionControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['sessionControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionControllerDeactivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return sessionControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerDeactivate>>
>;

export type SessionControllerDeactivateMutationError = unknown;

export const useSessionControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof sessionControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getSessionControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const sessionControllerActivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/session/${id}/activate`, method: 'PATCH' });
};

export const getSessionControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerActivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof sessionControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['sessionControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionControllerActivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return sessionControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerActivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerActivate>>
>;

export type SessionControllerActivateMutationError = unknown;

export const useSessionControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerActivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof sessionControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getSessionControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
