/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * App Service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AclControllerFindAllParams,
  CreateAclRequestDto,
  CreateAclResponseDto,
  DetailAclResponseDto,
  ListAclResponseDto,
  UpdateAclRequestDto,
  UpdateAclResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

/**
 * @summary Create a new application constant
 */
export const aclControllerCreate = (createAclRequestDto: CreateAclRequestDto, signal?: AbortSignal) => {
  return service<CreateAclResponseDto>({
    url: `/acl`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createAclRequestDto,
    signal,
  });
};

export const getAclControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aclControllerCreate>>,
    TError,
    { data: CreateAclRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aclControllerCreate>>,
  TError,
  { data: CreateAclRequestDto },
  TContext
> => {
  const mutationKey = ['aclControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof aclControllerCreate>>, { data: CreateAclRequestDto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return aclControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AclControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof aclControllerCreate>>>;
export type AclControllerCreateMutationBody = CreateAclRequestDto;
export type AclControllerCreateMutationError = unknown;

/**
 * @summary Create a new application constant
 */
export const useAclControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof aclControllerCreate>>,
      TError,
      { data: CreateAclRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof aclControllerCreate>>,
  TError,
  { data: CreateAclRequestDto },
  TContext
> => {
  const mutationOptions = getAclControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get all application constants
 */
export const aclControllerFindAll = (params?: AclControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListAclResponseDto>({ url: `/acl`, method: 'GET', params, signal });
};

export const getAclControllerFindAllQueryKey = (params?: AclControllerFindAllParams) => {
  return [`/acl`, ...(params ? [params] : [])] as const;
};

export const getAclControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof aclControllerFindAll>>,
  TError = ListAclResponseDto,
>(
  params?: AclControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindAll>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAclControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aclControllerFindAll>>> = ({ signal }) =>
    aclControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aclControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AclControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof aclControllerFindAll>>>;
export type AclControllerFindAllQueryError = ListAclResponseDto;

export function useAclControllerFindAll<
  TData = Awaited<ReturnType<typeof aclControllerFindAll>>,
  TError = ListAclResponseDto,
>(
  params: undefined | AclControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof aclControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof aclControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAclControllerFindAll<
  TData = Awaited<ReturnType<typeof aclControllerFindAll>>,
  TError = ListAclResponseDto,
>(
  params?: AclControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof aclControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof aclControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAclControllerFindAll<
  TData = Awaited<ReturnType<typeof aclControllerFindAll>>,
  TError = ListAclResponseDto,
>(
  params?: AclControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all application constants
 */

export function useAclControllerFindAll<
  TData = Awaited<ReturnType<typeof aclControllerFindAll>>,
  TError = ListAclResponseDto,
>(
  params?: AclControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAclControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get application constant by key
 */
export const aclControllerFindOne = (key: string, signal?: AbortSignal) => {
  return service<DetailAclResponseDto>({ url: `/acl/${key}`, method: 'GET', signal });
};

export const getAclControllerFindOneQueryKey = (key?: string) => {
  return [`/acl/${key}`] as const;
};

export const getAclControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof aclControllerFindOne>>,
  TError = unknown,
>(
  key: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindOne>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAclControllerFindOneQueryKey(key);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aclControllerFindOne>>> = ({ signal }) =>
    aclControllerFindOne(key, signal);

  return { queryKey, queryFn, enabled: !!key, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aclControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AclControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof aclControllerFindOne>>>;
export type AclControllerFindOneQueryError = unknown;

export function useAclControllerFindOne<TData = Awaited<ReturnType<typeof aclControllerFindOne>>, TError = unknown>(
  key: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof aclControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof aclControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAclControllerFindOne<TData = Awaited<ReturnType<typeof aclControllerFindOne>>, TError = unknown>(
  key: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof aclControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof aclControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAclControllerFindOne<TData = Awaited<ReturnType<typeof aclControllerFindOne>>, TError = unknown>(
  key: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get application constant by key
 */

export function useAclControllerFindOne<TData = Awaited<ReturnType<typeof aclControllerFindOne>>, TError = unknown>(
  key: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof aclControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAclControllerFindOneQueryOptions(key, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an application constant
 */
export const aclControllerUpdate = (id: number, updateAclRequestDto: UpdateAclRequestDto) => {
  return service<UpdateAclResponseDto>({
    url: `/acl/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAclRequestDto,
  });
};

export const getAclControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aclControllerUpdate>>,
    TError,
    { id: number; data: UpdateAclRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aclControllerUpdate>>,
  TError,
  { id: number; data: UpdateAclRequestDto },
  TContext
> => {
  const mutationKey = ['aclControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aclControllerUpdate>>,
    { id: number; data: UpdateAclRequestDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return aclControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AclControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof aclControllerUpdate>>>;
export type AclControllerUpdateMutationBody = UpdateAclRequestDto;
export type AclControllerUpdateMutationError = unknown;

/**
 * @summary Update an application constant
 */
export const useAclControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof aclControllerUpdate>>,
      TError,
      { id: number; data: UpdateAclRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof aclControllerUpdate>>,
  TError,
  { id: number; data: UpdateAclRequestDto },
  TContext
> => {
  const mutationOptions = getAclControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Deactivate an application constant
 */
export const aclControllerDeactivate = (id: number) => {
  return service<UpdateAclResponseDto>({ url: `/acl/${id}`, method: 'DELETE' });
};

export const getAclControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof aclControllerDeactivate>>, TError, { id: number }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof aclControllerDeactivate>>, TError, { id: number }, TContext> => {
  const mutationKey = ['aclControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof aclControllerDeactivate>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return aclControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AclControllerDeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof aclControllerDeactivate>>>;

export type AclControllerDeactivateMutationError = unknown;

/**
 * @summary Deactivate an application constant
 */
export const useAclControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof aclControllerDeactivate>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof aclControllerDeactivate>>, TError, { id: number }, TContext> => {
  const mutationOptions = getAclControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Activate an application constant
 */
export const aclControllerActivate = (id: number) => {
  return service<UpdateAclResponseDto>({ url: `/acl/${id}/activate`, method: 'PATCH' });
};

export const getAclControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof aclControllerActivate>>, TError, { id: number }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof aclControllerActivate>>, TError, { id: number }, TContext> => {
  const mutationKey = ['aclControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof aclControllerActivate>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return aclControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AclControllerActivateMutationResult = NonNullable<Awaited<ReturnType<typeof aclControllerActivate>>>;

export type AclControllerActivateMutationError = unknown;

/**
 * @summary Activate an application constant
 */
export const useAclControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof aclControllerActivate>>, TError, { id: number }, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof aclControllerActivate>>, TError, { id: number }, TContext> => {
  const mutationOptions = getAclControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
