export enum KEYS {
  ADMIN_USERS_LISTING = 'ADMIN_USERS_LISTING',
  ADMIN_USERS_DETAIL = 'ADMIN_USERS_DETAIL',
  BRANCH_LISTING = 'BRANCH_LISTING',
  BRANCH_DETAIL = 'BRANCH_DETAIL',
  VAN_LISTING = 'VAN_LISTING',
  VAN_DETAIL = 'VAN_DETAIL',
  ADMISSION_LISTING = 'ADMISSION_LISTING',
  ADMISSION_DETAIL = 'ADMISSION_DETAIL',
  QUESTION_SET_LISTING = 'QUESTION_SET_LISTING',
  QUESTION_SET_DETAIL = 'QUESTION_SET_DETAIL',
}
