/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AdminDetailResponseDto,
  AdminEnableLoginRequestDto,
  AdminEnableLoginResponseDto,
  AdminLoginFirebaseRequestDto,
  AdminLoginRequestDto,
  AdminLoginResponseDto,
  AdminRefreshRequestDto,
  AdminRefreshResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const adminAuthControllerLogin = (adminLoginRequestDto: AdminLoginRequestDto, signal?: AbortSignal) => {
  return service<AdminLoginResponseDto>({
    url: `/admin/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminLoginRequestDto,
    signal,
  });
};

export const getAdminAuthControllerLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLogin>>,
    TError,
    { data: AdminLoginRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>,
  TError,
  { data: AdminLoginRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthControllerLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerLogin>>,
    { data: AdminLoginRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof adminAuthControllerLogin>>>;
export type AdminAuthControllerLoginMutationBody = AdminLoginRequestDto;
export type AdminAuthControllerLoginMutationError = unknown;

export const useAdminAuthControllerLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthControllerLogin>>,
      TError,
      { data: AdminLoginRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>,
  TError,
  { data: AdminLoginRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthControllerLoginFirebase = (
  adminLoginFirebaseRequestDto: AdminLoginFirebaseRequestDto,
  signal?: AbortSignal,
) => {
  return service<AdminLoginResponseDto>({
    url: `/admin/auth/login-firebase`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminLoginFirebaseRequestDto,
    signal,
  });
};

export const getAdminAuthControllerLoginFirebaseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLoginFirebase>>,
    TError,
    { data: AdminLoginFirebaseRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerLoginFirebase>>,
  TError,
  { data: AdminLoginFirebaseRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthControllerLoginFirebase'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerLoginFirebase>>,
    { data: AdminLoginFirebaseRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthControllerLoginFirebase(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthControllerLoginFirebaseMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerLoginFirebase>>
>;
export type AdminAuthControllerLoginFirebaseMutationBody = AdminLoginFirebaseRequestDto;
export type AdminAuthControllerLoginFirebaseMutationError = unknown;

export const useAdminAuthControllerLoginFirebase = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthControllerLoginFirebase>>,
      TError,
      { data: AdminLoginFirebaseRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerLoginFirebase>>,
  TError,
  { data: AdminLoginFirebaseRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthControllerLoginFirebaseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthControllerRefresh = (adminRefreshRequestDto: AdminRefreshRequestDto, signal?: AbortSignal) => {
  return service<AdminRefreshResponseDto>({
    url: `/admin/auth/refresh`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminRefreshRequestDto,
    signal,
  });
};

export const getAdminAuthControllerRefreshMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerRefresh>>,
    TError,
    { data: AdminRefreshRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerRefresh>>,
  TError,
  { data: AdminRefreshRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthControllerRefresh'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerRefresh>>,
    { data: AdminRefreshRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthControllerRefresh(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthControllerRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerRefresh>>
>;
export type AdminAuthControllerRefreshMutationBody = AdminRefreshRequestDto;
export type AdminAuthControllerRefreshMutationError = unknown;

export const useAdminAuthControllerRefresh = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthControllerRefresh>>,
      TError,
      { data: AdminRefreshRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerRefresh>>,
  TError,
  { data: AdminRefreshRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthControllerRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthControllerLogout = (signal?: AbortSignal) => {
  return service<void>({ url: `/admin/auth/logout`, method: 'POST', signal });
};

export const getAdminAuthControllerLogoutMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof adminAuthControllerLogout>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof adminAuthControllerLogout>>, TError, void, TContext> => {
  const mutationKey = ['adminAuthControllerLogout'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAuthControllerLogout>>, void> = () => {
    return adminAuthControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerLogout>>
>;

export type AdminAuthControllerLogoutMutationError = unknown;

export const useAdminAuthControllerLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof adminAuthControllerLogout>>, TError, void, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof adminAuthControllerLogout>>, TError, void, TContext> => {
  const mutationOptions = getAdminAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthControllerGetAdminDetails = (signal?: AbortSignal) => {
  return service<AdminDetailResponseDto>({ url: `/admin/auth/me`, method: 'GET', signal });
};

export const getAdminAuthControllerGetAdminDetailsQueryKey = () => {
  return [`/admin/auth/me`] as const;
};

export const getAdminAuthControllerGetAdminDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminAuthControllerGetAdminDetailsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>> = ({ signal }) =>
    adminAuthControllerGetAdminDetails(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminAuthControllerGetAdminDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>
>;
export type AdminAuthControllerGetAdminDetailsQueryError = unknown;

export function useAdminAuthControllerGetAdminDetails<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
          TError,
          Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminAuthControllerGetAdminDetails<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
          TError,
          Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminAuthControllerGetAdminDetails<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAdminAuthControllerGetAdminDetails<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAuthControllerGetAdminDetails>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminAuthControllerGetAdminDetailsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const adminAuthControllerEnableLogin = (
  adminEnableLoginRequestDto: AdminEnableLoginRequestDto,
  signal?: AbortSignal,
) => {
  return service<AdminEnableLoginResponseDto>({
    url: `/admin/auth/enable-login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: adminEnableLoginRequestDto,
    signal,
  });
};

export const getAdminAuthControllerEnableLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerEnableLogin>>,
    TError,
    { data: AdminEnableLoginRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerEnableLogin>>,
  TError,
  { data: AdminEnableLoginRequestDto },
  TContext
> => {
  const mutationKey = ['adminAuthControllerEnableLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerEnableLogin>>,
    { data: AdminEnableLoginRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthControllerEnableLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthControllerEnableLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerEnableLogin>>
>;
export type AdminAuthControllerEnableLoginMutationBody = AdminEnableLoginRequestDto;
export type AdminAuthControllerEnableLoginMutationError = unknown;

export const useAdminAuthControllerEnableLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthControllerEnableLogin>>,
      TError,
      { data: AdminEnableLoginRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerEnableLogin>>,
  TError,
  { data: AdminEnableLoginRequestDto },
  TContext
> => {
  const mutationOptions = getAdminAuthControllerEnableLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
