/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * App Service
 * OpenAPI spec version: 1.0.0
 */
export interface AssetDetailResponseDto {
  id: string;
  title: string;
  mimeType: string;
  /** Short-lived signed URL */
  signedUrl: string;
  /** Expiry in seconds */
  expiresIn: number;
}

export interface UploadFileRequestDto {
  /** File to upload */
  file: Blob;
}

export interface AssetUploadResponseDto {
  id: string;
}

export interface AssetDeleteResponseDto {
  /** Message of the action */
  message: string;
}

export interface AdminLoginRequestDto {
  /** Admin email address */
  email: string;
  /**
   * Admin password
   * @minLength 6
   */
  password: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminLoginResponseDto {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** Token expiration time */
  expiresIn: number;
  /** Whether the user needs to change their temporary password */
  requiresPasswordChange: boolean;
}

export interface AdminLoginFirebaseRequestDto {
  /** Firebase ID token */
  idToken: string;
}

export interface AdminLoginGoogleRequestDto {
  /** Google ID token from react-native-google-signin or Google Sign-In */
  idToken: string;
}

export interface AdminRefreshRequestDto {
  /** JWT refresh token */
  refreshToken: string;
}

export interface AdminRefreshResponseDto {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** Token expiration time */
  expiresIn: number;
  /** Whether the user needs to change their temporary password */
  requiresPasswordChange: boolean;
}

export interface AdminUser {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
  /** The role of the admin user */
  role: string;
  /** Whether the admin user is active */
  isActive: boolean;
  /** Whether the admin user is forced to change their password */
  forcePasswordChange: boolean;
  /** Count of consecutive failed login attempts */
  failedLoginAttempts: number;
  /** Whether login is disabled due to failed attempts */
  isLoginDisabled: boolean;
  /** When the admin user was created */
  createdAt: string;
  /** When the admin user was last updated */
  updatedAt?: string;
  /** The temporary password of the admin user, used for initial login */
  tempPassword?: string;
}

export interface AdminDetailResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface AdminEnableLoginRequestDto {
  /** Admin user id to re-enable login for */
  adminUserId: string;
}

export interface AdminEnableLoginResponseDto {
  /** Message of the action */
  message: string;
}

export interface CreateAdminUserDto {
  /** Admin name */
  name: string;
  /** Admin email address */
  email: string;
}

export interface CreateAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface ListAdminUsersResponseDto {
  /** Total number of records */
  count: number;
  data: AdminUser[];
}

export interface DetailAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface UpdateAdminUserDto {
  /** Admin name */
  name?: string;
  /** Admin email address */
  email?: string;
}

export interface UpdateAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface ActionResponseDto {
  /** Message of the action */
  message: string;
}

export interface AdminChangePasswordRequestDto {
  /** Current password */
  currentPassword: string;
  /** New password */
  newPassword: string;
}

export interface AdminChangePasswordResponseDto {
  /** Success message */
  message: string;
}

export interface AdminForgotPasswordRequestDto {
  /** Admin email address */
  email: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminForgotPasswordResponseDto {
  /** Success message */
  message: string;
  /** Reset token */
  token: string;
}

export interface AdminResetPasswordRequestDto {
  /** Reset token received via email */
  token: string;
  /** New password */
  newPassword: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminResetPasswordResponseDto {
  /** Success message */
  message: string;
}

export interface AdminCreatePasswordRequestDto {
  /** New password to replace temporary password */
  newPassword: string;
}

export interface AdminCreatePasswordResponseDto {
  /** Success message */
  message: string;
}

export interface CreateAclRequestDto {
  key: string;
  value: string;
  description?: string;
  isPublic?: boolean;
}

export interface Acl {
  /** Whether the category is active */
  isActive: boolean;
  /** Created at timestamp */
  createdAt: string;
  /** Last updated timestamp */
  updatedAt?: string;
  id: number;
  key: string;
  value: string;
  description?: string;
}

export interface CreateAclResponseDto {
  message: string;
  data: Acl;
}

export interface ExtendedAcl {
  /** Whether the category is active */
  isActive: boolean;
  /** Created at timestamp */
  createdAt: string;
  /** Last updated timestamp */
  updatedAt?: string;
  id: number;
  key: string;
  value: string;
  description?: string;
}

export interface ListAclResponseDto {
  /** Total number of records */
  count: number;
  data: ExtendedAcl[];
}

export interface DetailAclResponseDto {
  data: ExtendedAcl;
}

export interface UpdateAclRequestDto {
  key: string;
  value?: string;
  description?: string;
}

export interface UpdateAclResponseDto {
  message: string;
  data: Acl;
}

export interface CreateBranchDto {
  /** code */
  code: string;
  /** name */
  name: string;
  /** defaultColorName */
  defaultColorName?: string;
  /** defaultColorHex (e.g. #FF5733) */
  defaultColorHex?: string;
}

export interface AdminUserBase {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
}

export interface Branch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** defaultColorName */
  defaultColorName?: string;
  /** defaultColorHex */
  defaultColorHex?: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateBranchResponseDto {
  /** Message of the action */
  message: string;
  data: Branch;
}

export interface ListBranchesResponseDto {
  /** Total number of records */
  count: number;
  data: Branch[];
}

export interface DetailBranchesResponseDto {
  /** Message of the action */
  message: string;
  data: Branch;
}

export interface UpdateBranchDto {
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** defaultColorName */
  defaultColorName?: string;
  /** defaultColorHex (e.g. #FF5733) */
  defaultColorHex?: string;
}

export interface UpdateBranchResponseDto {
  /** Message of the action */
  message: string;
  data?: Branch;
}

export interface CreateAreaDto {
  /** branchId */
  branchId: string;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan?: boolean;
  /** hasBoysVan */
  hasBoysVan?: boolean;
}

export interface AreaBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface Area {
  /** id */
  id: string;
  /** branch */
  branch: AreaBranch;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan: boolean;
  /** hasBoysVan */
  hasBoysVan: boolean;
  /** lastYearTotal */
  lastYearTotal: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateAreaResponseDto {
  /** Message of the action */
  message: string;
  data: Area;
}

export interface ListAreasResponseDto {
  /** Total number of records */
  count: number;
  data: Area[];
}

export interface DetailAreasResponseDto {
  /** Message of the action */
  message: string;
  data: Area;
}

export interface UpdateAreaDto {
  /** branchId */
  branchId?: string;
  /** alias */
  alias?: string;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** hasVan */
  hasVan?: boolean;
  /** hasBoysVan */
  hasBoysVan?: boolean;
}

export interface UpdateAreaResponseDto {
  /** Message of the action */
  message: string;
  data?: Area;
}

export interface CreateVanDto {
  /** branchId */
  branchId: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** colorName */
  colorName: string;
  /** colorHex (e.g. #FF5733) */
  colorHex: string;
  /** areaIds */
  areaIds?: string[];
}

export interface VanBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface VanArea {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** alias */
  alias: string;
}

export interface Van {
  /** id */
  id: string;
  /** branch */
  branch: VanBranch;
  /** code */
  code: string;
  /** name */
  name: string;
  /** colorName */
  colorName: string;
  /** colorHex */
  colorHex: string;
  /** areas */
  areas?: VanArea[];
  /** Male confirmed count (fees paid) */
  maleConfirmedCount?: number;
  /** Male applied count (fees not paid) */
  maleAppliedCount?: number;
  /** Female confirmed count (fees paid) */
  femaleConfirmedCount?: number;
  /** Female applied count (fees not paid) */
  femaleAppliedCount?: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateVanResponseDto {
  /** Message of the action */
  message: string;
  data: Van;
}

export interface ListVansResponseDto {
  /** Total number of records */
  count: number;
  data: Van[];
}

export interface DetailVansResponseDto {
  /** Message of the action */
  message: string;
  data: Van;
}

export interface UpdateVanDto {
  /** branchId */
  branchId?: string;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** colorName */
  colorName?: string;
  /** colorHex (e.g. #FF5733) */
  colorHex?: string;
  /** areaIds - replaces all existing area associations */
  areaIds?: string[];
}

export interface UpdateVanResponseDto {
  /** Message of the action */
  message: string;
  data?: Van;
}

export interface CreateSessionDto {
  /** name */
  name: string;
  /** attendanceDays */
  attendanceDays?: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
}

export interface Session {
  /** id */
  id: string;
  /** name */
  name: string;
  /** attendanceDays */
  attendanceDays: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateSessionResponseDto {
  /** Message of the action */
  message: string;
  data: Session;
}

export interface ListSessionsResponseDto {
  /** Total number of records */
  count: number;
  data: Session[];
}

export interface DetailSessionsResponseDto {
  /** Message of the action */
  message: string;
  data: Session;
}

export interface UpdateSessionDto {
  /** name */
  name?: string;
  /** attendanceDays */
  attendanceDays?: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
}

export interface UpdateSessionResponseDto {
  /** Message of the action */
  message: string;
  data?: Session;
}

export interface AttendanceDay {
  /** id */
  id: string;
  /** sessionId */
  sessionId: string;
  /** date */
  date: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface ListAttendanceDaysResponseDto {
  /** Total number of records */
  count: number;
  data: AttendanceDay[];
}

export type BulkAttendanceRecordItemDtoStatus =
  (typeof BulkAttendanceRecordItemDtoStatus)[keyof typeof BulkAttendanceRecordItemDtoStatus];

export const BulkAttendanceRecordItemDtoStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface BulkAttendanceRecordItemDto {
  /** admissionId */
  admissionId: string;
  status: BulkAttendanceRecordItemDtoStatus;
}

export interface BulkUpsertAttendanceRecordsDto {
  records: BulkAttendanceRecordItemDto[];
}

export interface BulkUpsertAttendanceRecordsResponseDto {
  /** Message of the action */
  message: string;
}

export type AttendanceSummaryRowStatus = (typeof AttendanceSummaryRowStatus)[keyof typeof AttendanceSummaryRowStatus];

export const AttendanceSummaryRowStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface AttendanceSummaryRow {
  /** classLevelId */
  classLevelId: string;
  status: AttendanceSummaryRowStatus;
  /** count */
  count: number;
}

export interface AttendanceSummaryResponseDto {
  /** Message of the action */
  message: string;
  data: AttendanceSummaryRow[];
}

export type StudentAttendanceHistoryRowStatus =
  (typeof StudentAttendanceHistoryRowStatus)[keyof typeof StudentAttendanceHistoryRowStatus];

export const StudentAttendanceHistoryRowStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface StudentAttendanceHistoryRow {
  /** attendanceDayId */
  attendanceDayId: string;
  /** date */
  date: string;
  status: StudentAttendanceHistoryRowStatus;
}

export interface StudentAttendanceHistoryResponseDto {
  /** Message of the action */
  message: string;
  data: StudentAttendanceHistoryRow[];
}

/**
 * group
 */
export type ClassLevelGroup = (typeof ClassLevelGroup)[keyof typeof ClassLevelGroup];

export const ClassLevelGroup = {
  TIFLAN: 'TIFLAN',
  MUHIBAN: 'MUHIBAN',
  NASIRAN: 'NASIRAN',
} as const;

/**
 * gender
 */
export type CreateClassLevelDtoGender = (typeof CreateClassLevelDtoGender)[keyof typeof CreateClassLevelDtoGender];

export const CreateClassLevelDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface CreateClassLevelDto {
  /** group */
  group: ClassLevelGroup;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: CreateClassLevelDtoGender;
  /** sortOrder */
  sortOrder?: number;
}

/**
 * gender
 */
export type ClassLevelGender = (typeof ClassLevelGender)[keyof typeof ClassLevelGender];

export const ClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface ClassLevel {
  /** group */
  group: ClassLevelGroup;
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: ClassLevelGender;
  /** sortOrder */
  sortOrder: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateClassLevelResponseDto {
  /** Message of the action */
  message: string;
  data: ClassLevel;
}

export interface ListClassLevelsResponseDto {
  /** Total number of records */
  count: number;
  data: ClassLevel[];
}

export interface DetailClassLevelsResponseDto {
  /** Message of the action */
  message: string;
  data: ClassLevel;
}

/**
 * gender
 */
export type UpdateClassLevelDtoGender = (typeof UpdateClassLevelDtoGender)[keyof typeof UpdateClassLevelDtoGender];

export const UpdateClassLevelDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface UpdateClassLevelDto {
  /** group */
  group?: ClassLevelGroup;
  /** age */
  age?: number;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** gender */
  gender?: UpdateClassLevelDtoGender;
  /** sortOrder */
  sortOrder?: number;
}

export interface UpdateClassLevelResponseDto {
  /** Message of the action */
  message: string;
  data?: ClassLevel;
}

/**
 * normalized gender (if possible)
 */
export type LegacyAdmissionPrefillGender =
  (typeof LegacyAdmissionPrefillGender)[keyof typeof LegacyAdmissionPrefillGender];

export const LegacyAdmissionPrefillGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface LegacyAdmissionPrefill {
  /** legacyStudentId */
  legacyStudentId?: string;
  /** branchId (auto-resolved if possible) */
  branchId?: string;
  /** areaId (auto-resolved if possible) */
  areaId?: string;
  /** student name */
  name?: string;
  /** father/guardian name */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  /** normalized gender (if possible) */
  gender?: LegacyAdmissionPrefillGender;
  /** phone */
  phone?: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber (B-Form/CNIC as text) */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
}

export interface LegacyAdmissionRaw {
  /** legacy grNo */
  grNo?: string;
  /** legacy area code (string) */
  area?: string;
  /** legacy city */
  city?: string;
  /** legacy imageUrl */
  imageUrl?: string;
}

export interface LegacyStudentRow {
  /** id */
  id: string;
  /** true if an admission already exists for this phone */
  alreadyRegistered: boolean;
  /** grNumber (legacy gr_no) */
  grNumber?: string;
  /** name */
  name?: string;
  /** fatherName (legacy fathers_name) */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  /** gender (legacy free-form text) */
  gender?: string;
  /** phone */
  phone?: string;
  /** identityNumber (legacy b_form_or_birth_certificate_no) */
  identityNumber?: string;
  /** isVerified */
  isVerified?: boolean;
  /** prefill payload for admission create form */
  prefill: LegacyAdmissionPrefill;
  /** warnings produced while building prefill */
  warnings: string[];
  /** raw legacy fields for display/debug */
  raw: LegacyAdmissionRaw;
}

export interface SearchLegacyAdmissionsResponseDto {
  /** Total number of records */
  count: number;
  data: LegacyStudentRow[];
}

export type CreateAdmissionDtoGender = (typeof CreateAdmissionDtoGender)[keyof typeof CreateAdmissionDtoGender];

export const CreateAdmissionDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface CreateAdmissionDto {
  /** sessionId */
  sessionId: string;
  /** legacyStudentId (optional for legacy prefill) */
  legacyStudentId?: string;
  /** branchId */
  branchId: string;
  /** areaId */
  areaId: string;
  /** student name */
  name: string;
  /** father/guardian name */
  fatherName: string;
  /** dateOfBirth */
  dateOfBirth: string;
  gender: CreateAdmissionDtoGender;
  /** phone */
  phone: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber (B-Form/CNIC as text) */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface AdmissionSession {
  /** id */
  id: string;
  /** name */
  name: string;
}

export type AdmissionStudentGender = (typeof AdmissionStudentGender)[keyof typeof AdmissionStudentGender];

export const AdmissionStudentGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionStudent {
  /** id */
  id: string;
  /** grNumber */
  grNumber: string;
  /** name */
  name: string;
  /** fatherName */
  fatherName: string;
  /** dateOfBirth */
  dateOfBirth: string;
  gender: AdmissionStudentGender;
  /** phone */
  phone: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber */
  identityNumber?: string;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface AdmissionInteractionTeacher {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
}

export interface AdmissionInteractionQuestionSet {
  /** id */
  id: string;
  /** title */
  title: string;
}

export interface AdmissionInteractionQuestion {
  /** id */
  id: string;
  /** prompt */
  prompt: string;
  /** sortOrder */
  sortOrder: number;
}

export interface AdmissionInteractionRating {
  /** id */
  id: string;
  /** rating */
  rating: number;
  /** notes */
  notes?: string;
  /** question */
  question: AdmissionInteractionQuestion;
}

export interface AdmissionInteraction {
  /** id */
  id: string;
  /** notes */
  notes?: string;
  /** teacher */
  teacher: AdmissionInteractionTeacher;
  /** questionSet */
  questionSet: AdmissionInteractionQuestionSet;
  /** ratings */
  ratings: AdmissionInteractionRating[];
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface AdmissionBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface AdmissionArea {
  /** id */
  id: string;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan: boolean;
  /** hasBoysVan */
  hasBoysVan: boolean;
}

/**
 * gender
 */
export type AdmissionClassLevelGender = (typeof AdmissionClassLevelGender)[keyof typeof AdmissionClassLevelGender];

export const AdmissionClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionClassLevel {
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: AdmissionClassLevelGender;
  /** group */
  group: ClassLevelGroup;
}

export type AdmissionStatus = (typeof AdmissionStatus)[keyof typeof AdmissionStatus];

export const AdmissionStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface Admission {
  /** id */
  id: string;
  status: AdmissionStatus;
  /** rejectedReason */
  rejectedReason?: string;
  /** session */
  session: AdmissionSession;
  /** student */
  student: AdmissionStudent;
  /** interaction */
  interaction?: AdmissionInteraction;
  /** branch */
  branch: AdmissionBranch;
  /** area */
  area: AdmissionArea;
  /** classLevel */
  classLevel: AdmissionClassLevel;
  /** classLevelGroup */
  classLevelGroup: ClassLevelGroup;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired: boolean;
  /** isMarried */
  isMarried: boolean;
  /** isWorking */
  isWorking: boolean;
  /** isFinalized */
  isFinalized: boolean;
  /** finalizedAt */
  finalizedAt?: string;
  /** finalizedByAdmin */
  finalizedByAdmin?: AdminUserBase;
  /** isFeePaid */
  isFeePaid: boolean;
  /** feePaidAt */
  feePaidAt?: string;
  /** feePaidByAdmin */
  feePaidByAdmin?: AdminUserBase;
  /** legacyStudentId */
  legacyStudentId?: string;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface CreateAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface ListAdmissionsResponseDto {
  /** Total number of records */
  count: number;
  data: Admission[];
}

/**
 * Admission status (UNVERIFIED, VERIFIED, REJECTED)
 */
export type AdmissionsDashboardStatusStatStatus =
  (typeof AdmissionsDashboardStatusStatStatus)[keyof typeof AdmissionsDashboardStatusStatStatus];

export const AdmissionsDashboardStatusStatStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface AdmissionsDashboardStatusStat {
  /** Admission status (UNVERIFIED, VERIFIED, REJECTED) */
  status: AdmissionsDashboardStatusStatStatus;
  /** Number of admissions in this status */
  count: number;
}

/**
 * Student gender (MALE, FEMALE)
 */
export type AdmissionsDashboardGenderStatGender =
  (typeof AdmissionsDashboardGenderStatGender)[keyof typeof AdmissionsDashboardGenderStatGender];

export const AdmissionsDashboardGenderStatGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionsDashboardGenderStat {
  /** Student gender (MALE, FEMALE) */
  gender: AdmissionsDashboardGenderStatGender;
  /** Number of admissions for this gender */
  count: number;
}

/**
 * Gender this class level is designated for
 */
export type AdmissionsDashboardClassLevelStatGender =
  (typeof AdmissionsDashboardClassLevelStatGender)[keyof typeof AdmissionsDashboardClassLevelStatGender];

export const AdmissionsDashboardClassLevelStatGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionsDashboardClassLevelStat {
  /** Class level code (e.g., "KG", "1", "2") */
  code: string;
  /** Class level display name (e.g., "Kindergarten", "Grade 1") */
  name: string;
  /** Gender this class level is designated for */
  gender: AdmissionsDashboardClassLevelStatGender;
  /** Number of admissions in this class level */
  count: number;
}

export interface AdmissionsDashboardAreaStat {
  /** Area ID */
  id: string;
  /** Area name */
  name: string;
  /** Tiflan male students count */
  tiflanMale: number;
  /** Tiflan female students count */
  tiflanFemale: number;
  /** Muhiban male students count */
  muhibanMale: number;
  /** Muhiban female students count */
  muhibanFemale: number;
  /** Nasiran male students count */
  nasiranMale: number;
  /** Nasiran female students count */
  nasiranFemale: number;
  /** Number of admissions this year (current session) */
  thisYear: number;
  /** Number of admissions from last year (stored in area.lastYearTotal) */
  lastYear: number;
  /** Year-over-year growth percentage formatted as string (e.g., "120.00%") */
  percentage: string;
}

export interface AdmissionsDashboardGroupStat {
  /** Class level group category */
  group: ClassLevelGroup;
  /** Number of male students in this group */
  maleCount: number;
  /** Number of female students in this group */
  femaleCount: number;
  /** Total students in this group (maleCount + femaleCount) */
  totalStudents: number;
}

export interface AdmissionsDashboardClassGenderStat {
  /** Class level code (e.g., "KG", "1", "2") */
  code: string;
  /** Class level display name (e.g., "Kindergarten", "Grade 1") */
  name: string;
  /** Number of male students in this class level */
  maleCount: number;
  /** Number of female students in this class level */
  femaleCount: number;
  /** Total students in this class level (maleCount + femaleCount) */
  totalStudents: number;
}

export interface AdmissionsDashboardClassFeeStats {
  /** Class level code (e.g., "KG", "1", "2") */
  code: string;
  /** Class level display name (e.g., "Kindergarten", "Grade 1") */
  name: string;
  /** Total expected students in this class level */
  expected: number;
  /** Number of students who have paid fee (confirmed) */
  feesPaid: number;
  /** Number of students who have not paid fee yet (expected - feesPaid) */
  remaining: number;
}

export interface FeeCardClassStat {
  /** Class level code (e.g., "Tiflan1", "Muhibaan5") */
  code: string;
  /** Class level display name */
  name: string;
  /** Total admissions (expected) */
  expected: number;
  /** Fee paid admissions (confirmed) */
  confirmed: number;
}

export interface FeeCardTotal {
  /** Total expected admissions */
  expected: number;
  /** Total confirmed (fee paid) admissions */
  confirmed: number;
}

export interface TiflanFeeCard {
  /** Fee stats for each Tiflan class (both genders combined) */
  classes: FeeCardClassStat[];
  /** Total expected and confirmed for Tiflan */
  total: FeeCardTotal;
}

export interface MuhibanFeeCard {
  /** Fee stats for each Muhiban class */
  classes: FeeCardClassStat[];
  /** Total expected and confirmed for this Muhiban gender */
  total: FeeCardTotal;
}

/**
 * Student gender
 */
export type FeeCardGenderStatGender = (typeof FeeCardGenderStatGender)[keyof typeof FeeCardGenderStatGender];

export const FeeCardGenderStatGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface FeeCardGenderStat {
  /** Student gender */
  gender: FeeCardGenderStatGender;
  /** Total admissions (expected) */
  expected: number;
  /** Fee paid admissions (confirmed) */
  confirmed: number;
}

export interface NasiranFeeCard {
  /** Fee stats for each gender in Nasiran */
  genders: FeeCardGenderStat[];
  /** Total expected and confirmed for Nasiran */
  total: FeeCardTotal;
}

export interface FeeCardStats {
  /** Tiflan fee card - all classes regardless of gender */
  tiflan: TiflanFeeCard;
  /** Muhiban Boys fee card - boys classes only */
  muhibanBoys: MuhibanFeeCard;
  /** Muhiban Girls fee card - girls classes only */
  muhibanGirls: MuhibanFeeCard;
  /** Nasiran fee card - breakdown by gender */
  nasiran: NasiranFeeCard;
}

export interface AdmissionsDashboardFunnel {
  /** Total number of active admissions */
  totalAdmissions: number;
  /** Number of admissions in UNVERIFIED status (pending document verification) */
  unverified?: number;
  /** Number of admissions in VERIFIED status (documents approved) */
  verified?: number;
  /** Number of admissions in REJECTED status */
  rejected?: number;
  /** Number of admissions where fee has been paid */
  feePaid: number;
  /** Number of admissions that have been finalized (enrollment complete) */
  finalized: number;
  /** Number of admissions where teacher interaction has been submitted */
  interactionSubmitted: number;
  /** Number of VERIFIED admissions that have NOT paid fee yet. Identifies students stuck after verification. */
  verifiedNotFeePaid: number;
  /** Number of fee-paid admissions that have NOT been finalized yet. Identifies students stuck after payment. */
  feePaidNotFinalized: number;
}

export interface AdmissionsDashboardRates {
  /** Percentage of total admissions that have paid fee (0-100, rounded to 2 decimals) */
  feePaidRate: number;
  /** Percentage of total admissions that have been finalized (0-100, rounded to 2 decimals) */
  finalizedRate: number;
  /** Percentage of total admissions that have completed teacher interaction (0-100, rounded to 2 decimals) */
  interactionSubmittedRate: number;
}

export interface AdmissionsDashboardAverages {
  /** Average number of days from admission creation to fee payment. Null if no fee-paid admissions exist. */
  avgDaysToFeePaid?: number;
  /** Average number of days from admission creation to finalization. Null if no finalized admissions exist. */
  avgDaysToFinalized?: number;
}

export interface AdmissionsDashboardTrendPoint {
  /** Date in ISO format (YYYY-MM-DD) */
  date: string;
  /** Number of admissions created on this date */
  admissionsCreated: number;
  /** Number of teacher interactions submitted on this date */
  interactionsSubmitted: number;
}

export interface AdmissionsDashboardResponseData {
  /** Timestamp when this dashboard data was generated */
  generatedAt: string;
  /** Session ID filter applied (if any) */
  sessionId?: string;
  /** Branch ID filter applied (if any) */
  branchId?: string;
  /** Number of days in the recentTrend time series */
  days: number;
  /** Admission counts grouped by status */
  statusStats: AdmissionsDashboardStatusStat[];
  /** Admission counts grouped by student gender */
  genderStats: AdmissionsDashboardGenderStat[];
  /** Admission counts grouped by class level */
  classLevelStats: AdmissionsDashboardClassLevelStat[];
  /** Admission counts grouped by area with year-over-year comparison */
  areaStats: AdmissionsDashboardAreaStat[];
  /** Admission counts grouped by class level group with gender breakdown */
  groupStats: AdmissionsDashboardGroupStat[];
  /** Admission counts grouped by class level (e.g. KG, Grade 1) with male/female breakdown */
  classGenderStats: AdmissionsDashboardClassGenderStat[];
  /** Admission counts grouped by class level (e.g. KG, Grade 1) with fee paid/not paid breakdown */
  classFeeStats: AdmissionsDashboardClassFeeStats[];
  /** Fee card stats for the 4 frontend cards (Tiflan, Muhiban Boys, Muhiban Girls, Nasiran) */
  feeCardStats: FeeCardStats;
  /** Funnel metrics showing admission progression and bottlenecks */
  funnel: AdmissionsDashboardFunnel;
  /** Conversion rate percentages for key milestones */
  rates: AdmissionsDashboardRates;
  /** Average time metrics for admission process steps */
  averages: AdmissionsDashboardAverages;
  /** Day-by-day time series of admissions created and interactions submitted. Includes all days in the range (including zero-count days) for proper chart rendering. */
  recentTrend: AdmissionsDashboardTrendPoint[];
}

export interface AdmissionsDashboardResponseDto {
  /** Message of the action */
  message: string;
  /** Dashboard statistics and metrics */
  data: AdmissionsDashboardResponseData;
}

export interface DetailAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export type UpdateAdmissionDtoGender = (typeof UpdateAdmissionDtoGender)[keyof typeof UpdateAdmissionDtoGender];

export const UpdateAdmissionDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface UpdateAdmissionDto {
  /** branchId */
  branchId?: string;
  /** areaId */
  areaId?: string;
  /** student name */
  name?: string;
  /** father/guardian name */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  gender?: UpdateAdmissionDtoGender;
  /** phone */
  phone?: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface UpdateAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data?: Admission;
}

export type UpdateAdmissionStatusDtoStatus =
  (typeof UpdateAdmissionStatusDtoStatus)[keyof typeof UpdateAdmissionStatusDtoStatus];

export const UpdateAdmissionStatusDtoStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface UpdateAdmissionStatusDto {
  status: UpdateAdmissionStatusDtoStatus;
  /** rejectedReason (required when status=REJECTED) */
  rejectedReason?: string;
}

export interface UpdateAdmissionStatusResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface MarkFeePaidDto {
  /** isFeePaid */
  isFeePaid: boolean;
}

export interface MarkFeePaidResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface FinalizeAdmissionDto {
  /** isFinalized */
  isFinalized: boolean;
}

export interface FinalizeAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

/**
 * Gender
 */
export type InteractionStudentGender = (typeof InteractionStudentGender)[keyof typeof InteractionStudentGender];

export const InteractionStudentGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface InteractionStudent {
  /** Student ID */
  id: string;
  /** GR Number */
  grNumber: string;
  /** Student name */
  name: string;
  /** Father name */
  fatherName: string;
  /** Gender */
  gender: InteractionStudentGender;
}

/**
 * Session
 */
export type InteractionAdmissionSession = { [key: string]: unknown };

/**
 * Branch
 */
export type InteractionAdmissionBranch = { [key: string]: unknown };

/**
 * Area
 */
export type InteractionAdmissionArea = { [key: string]: unknown };

/**
 * Class Level
 */
export type InteractionAdmissionClassLevel = { [key: string]: unknown };

export interface InteractionAdmission {
  /** Admission ID */
  id: string;
  /** Session */
  session: InteractionAdmissionSession;
  /** Branch */
  branch: InteractionAdmissionBranch;
  /** Area */
  area: InteractionAdmissionArea;
  /** Class Level */
  classLevel: InteractionAdmissionClassLevel;
}

export interface InteractionQuestionSet {
  /** Question Set ID */
  id: string;
  /** Question Set title */
  title: string;
}

export interface InteractionQuestion {
  /** Question ID */
  id: string;
  /** Question prompt */
  prompt: string;
  /** Sort order */
  sortOrder: number;
}

export interface InteractionRating {
  /** Rating ID */
  id: string;
  /** Rating value (1-5) */
  rating: number;
  /** Rating notes */
  notes?: string;
  /** Question */
  question: InteractionQuestion;
}

export interface Interaction {
  /** Interaction ID */
  id: string;
  /** Overall notes */
  notes?: string;
  /** Teacher who conducted the interaction */
  teacher: AdminUserBase;
  /** Student info */
  student: InteractionStudent;
  /** Admission info */
  admission: InteractionAdmission;
  /** Question Set */
  questionSet: InteractionQuestionSet;
  /** Ratings */
  ratings: InteractionRating[];
  /** Created at */
  createdAt: string;
  /** Updated at */
  updatedAt?: string;
}

export interface ListInteractionsResponseDto {
  /** Total number of records */
  count: number;
  data: Interaction[];
}

export interface DashboardSession {
  id: string;
  name: string;
}

export type DashboardClassLevelGender = (typeof DashboardClassLevelGender)[keyof typeof DashboardClassLevelGender];

export const DashboardClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface DashboardClassLevel {
  id: string;
  code: string;
  name: string;
  age: number;
  gender: DashboardClassLevelGender;
}

export interface DashboardBranch {
  id: string;
  code: string;
  name: string;
}

export interface DashboardQuestionSet {
  id: string;
  title: string;
}

/**
 * Area info
 */
export type StudentWithRatingArea = { [key: string]: unknown };

export interface StudentWithRating {
  /** GR Number */
  grNumber: string;
  /** Student name */
  name: string;
  /** Area info */
  area: StudentWithRatingArea;
  /** The rating they gave */
  rating: number;
}

export interface QuestionStats {
  /** Question ID */
  questionId: string;
  /** Question prompt */
  prompt: string;
  /** Sort order */
  sortOrder: number;
  /** Total number of ratings */
  totalRatings: number;
  /** Average rating (1-5) */
  averageRating: number;
  /** Count of rating = 1 */
  rating1Count: number;
  /** Count of rating = 2 */
  rating2Count: number;
  /** Count of rating = 3 */
  rating3Count: number;
  /** Count of rating = 4 */
  rating4Count: number;
  /** Count of rating = 5 */
  rating5Count: number;
  /** Count of ratings <= 2 (rating1Count + rating2Count) */
  lowRatingCount: number;
  /** Percentage of ratings <= 2 */
  lowRatingPercentage: number;
  /** Students with rating = 5 (best performers, can teach others) */
  studentsBest: StudentWithRating[];
  /** Students with rating = 3 (average performers) */
  studentsAverage: StudentWithRating[];
  /** Students with rating <= 2 (need attention) */
  studentsNeedingAttention: StudentWithRating[];
}

/**
 * Best performing question
 */
export type DashboardInsightsBestQuestion = { [key: string]: unknown };

/**
 * Worst performing question
 */
export type DashboardInsightsWorstQuestion = { [key: string]: unknown };

export interface DashboardInsights {
  /** Overall average rating across all questions */
  overallAverageRating: number;
  /** Best performing question */
  bestQuestion?: DashboardInsightsBestQuestion;
  /** Worst performing question */
  worstQuestion?: DashboardInsightsWorstQuestion;
  /** Count of questions with average < 3.0 */
  questionsNeedingAttention: number;
  /** Count of unique students with any low rating */
  totalStudentsNeedingAttention: number;
}

export interface InteractionsDashboardData {
  /** Timestamp when dashboard was generated */
  generatedAt: string;
  /** Session info */
  session: DashboardSession;
  /** Class level info */
  classLevel: DashboardClassLevel;
  /** Branch info */
  branch: DashboardBranch;
  /** Question set info */
  questionSet?: DashboardQuestionSet;
  /** Total number of interactions */
  totalInteractions: number;
  /** All questions with stats sorted by sortOrder */
  questions: QuestionStats[];
  /** Insights derived from all questions */
  insights: DashboardInsights;
}

export interface InteractionsDashboardResponseDto {
  /** Message of the action */
  message: string;
  data: InteractionsDashboardData;
}

export interface InteractionTemplateStudent {
  id: string;
  grNumber: string;
  name: string;
  fatherName: string;
}

export interface InteractionTemplateAdmission {
  id: string;
  sessionId: string;
  classLevelId: string;
}

export interface InteractionTemplateQuestionSet {
  id: string;
  title: string;
}

export interface InteractionTemplate {
  student: InteractionTemplateStudent;
  admission: InteractionTemplateAdmission;
  questionSet: InteractionTemplateQuestionSet;
  questions: InteractionQuestion[];
}

export interface GetInteractionTemplateResponseDto {
  /** Message of the action */
  message: string;
  data: InteractionTemplate;
}

export interface CreateInteractionRatingDto {
  /** Question id */
  questionId: string;
  /**
   * Rating value (1..5)
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** Optional notes for this question */
  notes?: string;
}

export interface CreateInteractionDto {
  /** Admission id (session-specific) */
  admissionId: string;
  /** Overall notes for interaction */
  notes?: string;
  ratings: CreateInteractionRatingDto[];
}

export interface CreateInteractionResponseData {
  id: string;
  admissionId: string;
}

export interface CreateInteractionResponseDto {
  /** Message of the action */
  message: string;
  data: CreateInteractionResponseData;
}

export interface CreateQuestionSetQuestionDto {
  /** prompt */
  prompt: string;
  /** sortOrder (defaults to array index) */
  sortOrder?: number;
}

export interface CreateQuestionSetDto {
  /** sessionId */
  sessionId: string;
  /** classLevelId */
  classLevelId: string;
  /** title */
  title: string;
  /** questions */
  questions: CreateQuestionSetQuestionDto[];
}

export interface QuestionSetSession {
  /** id */
  id: string;
  /** name */
  name: string;
}

/**
 * gender
 */
export type QuestionSetClassLevelGender =
  (typeof QuestionSetClassLevelGender)[keyof typeof QuestionSetClassLevelGender];

export const QuestionSetClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface QuestionSetClassLevel {
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: QuestionSetClassLevelGender;
}

export interface QuestionSetQuestion {
  /** id */
  id: string;
  /** prompt */
  prompt: string;
  /** sortOrder */
  sortOrder: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface QuestionSet {
  /** id */
  id: string;
  /** session */
  session: QuestionSetSession;
  /** classLevel */
  classLevel: QuestionSetClassLevel;
  /** title */
  title: string;
  /** questions */
  questions: QuestionSetQuestion[];
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface CreateQuestionSetResponseDto {
  /** Message of the action */
  message: string;
  data: QuestionSet;
}

export interface ListQuestionSetsResponseDto {
  /** Total number of records */
  count: number;
  data: QuestionSet[];
}

export interface DetailQuestionSetsResponseDto {
  /** Message of the action */
  message: string;
  data: QuestionSet;
}

export interface UpdateQuestionSetDto {
  /** sessionId */
  sessionId?: string;
  /** classLevelId */
  classLevelId?: string;
  /** title */
  title?: string;
  /** Replace all questions when provided (full replacement) */
  questions?: CreateQuestionSetQuestionDto[];
}

export interface UpdateQuestionSetResponseDto {
  /** Message of the action */
  message: string;
  data?: QuestionSet;
}

export interface ImportLegacyStudentsRequestDto {
  /** CSV file to import */
  file: Blob;
}

export interface ImportLegacyStudentsResponseDto {
  /** Message of the action */
  message: string;
  /** Total records processed */
  totalProcessed: number;
  /** Records successfully imported */
  successCount: number;
  /** Records inserted */
  insertedCount?: number;
  /** Records updated */
  updatedCount?: number;
  /** Records skipped (duplicates) */
  skippedCount: number;
  /** Records that failed to import */
  errorCount: number;
  /** Error details */
  errors?: string[];
}

export interface LegacyStudent {
  /** Unique identifier */
  id: string;
  /** Student name */
  name?: string;
  /** Father's name */
  fathersName?: string;
  /** Date of birth */
  dateOfBirth?: string;
  /** Address */
  address?: string;
  /** Area */
  area?: string;
  /** City */
  city?: string;
  /** Is school going */
  isSchoolGoing?: string;
  /** School name */
  schoolName?: string;
  /** School class */
  schoolClass?: string;
  /** Previously attended madressa */
  previouslyAttendedMadressa?: string;
  /** Previously attended year */
  previouslyAttendedYear?: string;
  /** Previously attended class */
  previouslyAttendedClass?: string;
  /** Phone number */
  phoneNumber?: string;
  /** WhatsApp number */
  whatsappNumber?: string;
  /** Gender */
  gender?: string;
  /** Is married */
  isMarried?: string;
  /** Is working */
  isWorking?: string;
  /** Work type */
  workType?: string;
  /** Email address */
  emailAddress?: string;
  /** Is van required */
  isVanRequired?: string;
  /** Is verified */
  isVerified?: boolean;
  /** Card printed */
  cardPrinted?: boolean;
  /** Van stop */
  vanStop?: string;
  /** B-Form or birth certificate number */
  bFormOrBirthCertificateNo?: string;
  /** GR number */
  grNo?: string;
  /** Category */
  category?: string;
  /** Image URL */
  imageUrl?: string;
  /** Is fees paid */
  isFeesPaid?: string;
  /** Updated by */
  updatedBy?: string;
  /** Admission year */
  admissionYear?: string;
  /** Created at */
  createdAt: string;
  /** Updated at */
  updatedAt?: string;
}

export interface ListLegacyStudentsResponseDto {
  /** Total count */
  count: number;
  /** List of legacy students */
  data: LegacyStudent[];
}

export interface ClearLegacyStudentsRequestDto {
  /** Confirm deletion */
  confirm: boolean;
}

export interface ClearLegacyStudentsResponseDto {
  /** Message of the action */
  message: string;
  /** Number of records deleted */
  deletedCount: number;
}

export interface IdCardArea {
  name: string;
  alias: string;
  hasVan: boolean;
  hasBoysVan: boolean;
}

export interface IdCardBranch {
  code: string;
  name: string;
  defaultColorHex?: string;
}

export interface IdCardClassLevel {
  code: string;
  name: string;
  group: ClassLevelGroup;
}

export interface IdCardVan {
  name: string;
  colorHex: string;
  colorName: string;
}

export type IdCardStudentGender = (typeof IdCardStudentGender)[keyof typeof IdCardStudentGender];

export const IdCardStudentGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface IdCardStudent {
  grNumber: string;
  name: string;
  fatherName: string;
  dateOfBirth: string;
  phone: string;
  alternatePhone?: string;
  gender: IdCardStudentGender;
  area: IdCardArea;
  branch: IdCardBranch;
  classLevel: IdCardClassLevel;
  van?: IdCardVan;
  /** Computed ribbon color based on van rules */
  ribbonColorHex: string;
  /** Computed ribbon color name based on van rules */
  ribbonColorName: string;
}

export interface IdCardPreviewResponseDto {
  /** Total number of records */
  count: number;
  data: IdCardStudent[];
}

/**
 * Admission status filter
 */
export type IdCardFilterDtoStatus = (typeof IdCardFilterDtoStatus)[keyof typeof IdCardFilterDtoStatus];

export const IdCardFilterDtoStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

/**
 * Gender filter
 */
export type IdCardFilterDtoGender = (typeof IdCardFilterDtoGender)[keyof typeof IdCardFilterDtoGender];

export const IdCardFilterDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface IdCardFilterDto {
  /** Specific admission IDs to generate cards for. When provided, other filters are ignored. */
  admissionIds?: string[];
  /** Session ID (required when admissionIds is not provided) */
  sessionId: string;
  /** Branch ID */
  branchId?: string;
  /** Area ID */
  areaId?: string;
  /** Van ID (filters via area-van relationship) */
  vanId?: string;
  /** Class Level ID */
  classLevelId?: string;
  /** Class Level Group */
  classLevelGroup?: string;
  /** Admission status filter */
  status?: IdCardFilterDtoStatus;
  /** Fee paid status */
  isFeePaid?: boolean;
  /** Finalization status */
  isFinalized?: boolean;
  /** Gender filter */
  gender?: IdCardFilterDtoGender;
}

export type SittingSlipStudentGender = (typeof SittingSlipStudentGender)[keyof typeof SittingSlipStudentGender];

export const SittingSlipStudentGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface SittingSlipStudent {
  grNumber: string;
  name: string;
  fatherName: string;
  gender: SittingSlipStudentGender;
}

export interface SittingSlipPreviewResponseDto {
  /** Total number of records */
  count: number;
  data: SittingSlipStudent[];
}

/**
 * Gender filter
 */
export type SittingSlipFilterDtoGender = (typeof SittingSlipFilterDtoGender)[keyof typeof SittingSlipFilterDtoGender];

export const SittingSlipFilterDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface SittingSlipFilterDto {
  /** Specific admission IDs to generate slips for. When provided, other filters are ignored. */
  admissionIds?: string[];
  /** Session ID (required when admissionIds is not provided) */
  sessionId: string;
  /** Branch ID */
  branchId?: string;
  /** Area ID */
  areaId?: string;
  /** Gender filter */
  gender?: SittingSlipFilterDtoGender;
}

export type AttendanceStudentGender = (typeof AttendanceStudentGender)[keyof typeof AttendanceStudentGender];

export const AttendanceStudentGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AttendanceStudent {
  grNumber: string;
  name: string;
  fatherName: string;
  phone: string;
  gender: AttendanceStudentGender;
  className: string;
  areaName: string;
  areaAlias: string;
}

export interface AttendanceSheetPreviewResponseDto {
  /** Total number of records */
  count: number;
  /** Area name */
  areaName?: string;
  /** Area alias */
  areaAlias?: string;
  data: AttendanceStudent[];
}

/**
 * Gender filter
 */
export type AttendanceSheetFilterDtoGender =
  (typeof AttendanceSheetFilterDtoGender)[keyof typeof AttendanceSheetFilterDtoGender];

export const AttendanceSheetFilterDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AttendanceSheetFilterDto {
  /** Session ID (required) */
  sessionId: string;
  /** Area ID (required - generates per area) */
  areaId: string;
  /** Gender filter */
  gender?: AttendanceSheetFilterDtoGender;
  /** Class level groups to include (default: MUHIBAN, NASIRAN) */
  classLevelGroups?: ClassLevelGroup[];
}

/**
 * Admission status filter
 */
export type VerificationSlipFilterDtoStatus =
  (typeof VerificationSlipFilterDtoStatus)[keyof typeof VerificationSlipFilterDtoStatus];

export const VerificationSlipFilterDtoStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

/**
 * Gender filter
 */
export type VerificationSlipFilterDtoGender =
  (typeof VerificationSlipFilterDtoGender)[keyof typeof VerificationSlipFilterDtoGender];

export const VerificationSlipFilterDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface VerificationSlipFilterDto {
  /** Specific admission IDs to generate cards for. When provided, other filters are ignored. */
  admissionIds?: string[];
  /** Session ID (required when admissionIds is not provided) */
  sessionId: string;
  /** Branch ID */
  branchId?: string;
  /** Area ID */
  areaId?: string;
  /** Van ID (filters via area-van relationship) */
  vanId?: string;
  /** Class Level ID */
  classLevelId?: string;
  /** Class Level Group */
  classLevelGroup?: string;
  /** Admission status filter */
  status?: VerificationSlipFilterDtoStatus;
  /** Fee paid status */
  isFeePaid?: boolean;
  /** Finalization status */
  isFinalized?: boolean;
  /** Gender filter */
  gender?: VerificationSlipFilterDtoGender;
}

export interface VerificationSlipStudent {
  admissionId: string;
  grNumber: string;
  name: string;
  fatherName: string;
  /** @nullable */
  dateOfBirth: string | null;
  className: string;
  classLevelGroup: ClassLevelGroup;
  areaName: string;
  areaAlias: string;
  branchName: string;
}

export interface VerificationSlipPreviewResponseDto {
  /** Total number of students */
  count: number;
  /** Student data for verification slips */
  data: VerificationSlipStudent[];
}

export interface CardPrintRequestStudentInfo {
  grNumber: string;
  name: string;
  fatherName: string;
}

export interface CardPrintRequestBranchInfo {
  code: string;
  name: string;
}

export interface CardPrintRequestAreaInfo {
  name: string;
  alias: string;
}

export interface CardPrintRequestClassLevelInfo {
  name: string;
}

export interface CardPrintRequestAdmissionInfo {
  student: CardPrintRequestStudentInfo;
  branch: CardPrintRequestBranchInfo;
  area: CardPrintRequestAreaInfo;
  classLevel: CardPrintRequestClassLevelInfo;
}

export type CardPrintRequestEntityStatus =
  (typeof CardPrintRequestEntityStatus)[keyof typeof CardPrintRequestEntityStatus];

export const CardPrintRequestEntityStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface CardPrintRequestEntity {
  id: string;
  admissionId: string;
  status: CardPrintRequestEntityStatus;
  sessionId: string;
  branchId: string;
  requestedAt: string;
  requestedById?: string;
  completedAt?: string;
  completedById?: string;
  printBatchId?: string;
  printedFilePath?: string;
  createdAt: string;
  updatedAt?: string;
  admission: CardPrintRequestAdmissionInfo;
}

export interface ListCardPrintRequestsResponseDto {
  /** Total number of records */
  count: number;
  data: CardPrintRequestEntity[];
}

/**
 * Count by status
 */
export type CountCardPrintRequestsResponseDtoByStatus = { [key: string]: unknown };

export interface CountCardPrintRequestsResponseDto {
  /** Total count of matching requests */
  count: number;
  /** Count by status */
  byStatus?: CountCardPrintRequestsResponseDtoByStatus;
}

/**
 * Status filter (defaults to PENDING)
 */
export type ProcessCardPrintRequestsDtoStatus =
  (typeof ProcessCardPrintRequestsDtoStatus)[keyof typeof ProcessCardPrintRequestsDtoStatus];

export const ProcessCardPrintRequestsDtoStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface ProcessCardPrintRequestsDto {
  /** Session ID (required when admissionIds not provided) */
  sessionId?: string;
  /** Branch ID (required when admissionIds not provided) */
  branchId?: string;
  /** Status filter (defaults to PENDING) */
  status?: ProcessCardPrintRequestsDtoStatus;
  /** Specific admission IDs to process. When provided, sessionId and branchId filters are ignored. */
  admissionIds?: string[];
}

export interface ProcessCardPrintRequestsResponseDto {
  /** Success message */
  message: string;
  /** Number of cards generated */
  cardCount: number;
  /** Number of requests processed */
  requestsProcessed: number;
  /** Batch ID for this print job */
  batchId: string;
  /** Firebase storage path to the generated PDF */
  filePath: string;
}

export interface CreateCardPrintRequestDto {
  /** Admission IDs to create card print requests for */
  admissionIds: string[];
}

export interface CreateCardPrintRequestResponseDto {
  /** Success message */
  message: string;
  /** Number of requests created */
  created: number;
  /** Number of requests that already existed (skipped) */
  skipped: number;
}

export interface CancelCardPrintRequestResponseDto {
  /** Success message */
  message: string;
  data: CardPrintRequestEntity;
}

export type AssetsControllerUploadPublicParams = {
  type: AssetsControllerUploadPublicType;
  /**
   * Category of the asset
   */
  category: string;
};

export type AssetsControllerUploadPublicType =
  (typeof AssetsControllerUploadPublicType)[keyof typeof AssetsControllerUploadPublicType];

export const AssetsControllerUploadPublicType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
} as const;

export type AdminUsersControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdminUsersControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * Email of the admin user
   */
  email?: string;
  /**
   * Name of the admin user
   */
  name?: string;
  /**
   * Sort by
   */
  sortBy?: AdminUsersControllerFindAllSortBy;
};

export type AdminUsersControllerFindAllSortOrder =
  (typeof AdminUsersControllerFindAllSortOrder)[keyof typeof AdminUsersControllerFindAllSortOrder];

export const AdminUsersControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdminUsersControllerFindAllSortBy =
  (typeof AdminUsersControllerFindAllSortBy)[keyof typeof AdminUsersControllerFindAllSortBy];

export const AdminUsersControllerFindAllSortBy = {
  id: 'id',
  name: 'name',
  email: 'email',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AclControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AclControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  key?: string;
  value?: string;
  id?: number;
  sortBy?: AclControllerFindAllSortBy;
  /**
   * Include non-public records
   */
  includeNonPublic?: boolean;
};

export type AclControllerFindAllSortOrder =
  (typeof AclControllerFindAllSortOrder)[keyof typeof AclControllerFindAllSortOrder];

export const AclControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AclControllerFindAllSortBy = (typeof AclControllerFindAllSortBy)[keyof typeof AclControllerFindAllSortBy];

export const AclControllerFindAllSortBy = {
  id: 'id',
  key: 'key',
  value: 'value',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type BranchControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: BranchControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * Sort by
   */
  sortBy?: BranchControllerFindAllSortBy;
};

export type BranchControllerFindAllSortOrder =
  (typeof BranchControllerFindAllSortOrder)[keyof typeof BranchControllerFindAllSortOrder];

export const BranchControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type BranchControllerFindAllSortBy =
  (typeof BranchControllerFindAllSortBy)[keyof typeof BranchControllerFindAllSortBy];

export const BranchControllerFindAllSortBy = {
  id: 'id',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type BranchControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AreaControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AreaControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * branchId
   */
  branchId?: string;
  /**
   * alias
   */
  alias?: string;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * hasVan
   */
  hasVan?: boolean;
  /**
   * hasBoysVan
   */
  hasBoysVan?: boolean;
  /**
   * Sort by
   */
  sortBy?: AreaControllerFindAllSortBy;
};

export type AreaControllerFindAllSortOrder =
  (typeof AreaControllerFindAllSortOrder)[keyof typeof AreaControllerFindAllSortOrder];

export const AreaControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AreaControllerFindAllSortBy =
  (typeof AreaControllerFindAllSortBy)[keyof typeof AreaControllerFindAllSortBy];

export const AreaControllerFindAllSortBy = {
  id: 'id',
  branchId: 'branchId',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AreaControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type VanControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: VanControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * branchId
   */
  branchId?: string;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * sessionId - Filter admission counts by session
   */
  sessionId?: string;
  /**
   * Sort by
   */
  sortBy?: VanControllerFindAllSortBy;
};

export type VanControllerFindAllSortOrder =
  (typeof VanControllerFindAllSortOrder)[keyof typeof VanControllerFindAllSortOrder];

export const VanControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type VanControllerFindAllSortBy = (typeof VanControllerFindAllSortBy)[keyof typeof VanControllerFindAllSortBy];

export const VanControllerFindAllSortBy = {
  id: 'id',
  branchId: 'branchId',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type VanControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type SessionControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: SessionControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * name
   */
  name?: string;
  /**
   * Sort by
   */
  sortBy?: SessionControllerFindAllSortBy;
};

export type SessionControllerFindAllSortOrder =
  (typeof SessionControllerFindAllSortOrder)[keyof typeof SessionControllerFindAllSortOrder];

export const SessionControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type SessionControllerFindAllSortBy =
  (typeof SessionControllerFindAllSortBy)[keyof typeof SessionControllerFindAllSortBy];

export const SessionControllerFindAllSortBy = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type SessionControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AttendanceControllerListDaysParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AttendanceControllerListDaysSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * sessionId
   */
  sessionId: string;
  /**
   * Sort by
   */
  sortBy?: AttendanceControllerListDaysSortBy;
};

export type AttendanceControllerListDaysSortOrder =
  (typeof AttendanceControllerListDaysSortOrder)[keyof typeof AttendanceControllerListDaysSortOrder];

export const AttendanceControllerListDaysSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AttendanceControllerListDaysSortBy =
  (typeof AttendanceControllerListDaysSortBy)[keyof typeof AttendanceControllerListDaysSortBy];

export const AttendanceControllerListDaysSortBy = {
  date: 'date',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AttendanceControllerStudentHistoryParams = {
  sessionId: string;
};

export type ClassLevelControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: ClassLevelControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * age
   */
  age?: number;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * gender
   */
  gender?: ClassLevelControllerFindAllGender;
  /**
   * Sort by
   */
  sortBy?: ClassLevelControllerFindAllSortBy;
};

export type ClassLevelControllerFindAllSortOrder =
  (typeof ClassLevelControllerFindAllSortOrder)[keyof typeof ClassLevelControllerFindAllSortOrder];

export const ClassLevelControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ClassLevelControllerFindAllGender =
  (typeof ClassLevelControllerFindAllGender)[keyof typeof ClassLevelControllerFindAllGender];

export const ClassLevelControllerFindAllGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export type ClassLevelControllerFindAllSortBy =
  (typeof ClassLevelControllerFindAllSortBy)[keyof typeof ClassLevelControllerFindAllSortBy];

export const ClassLevelControllerFindAllSortBy = {
  id: 'id',
  age: 'age',
  code: 'code',
  name: 'name',
  gender: 'gender',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ClassLevelControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AdmissionsControllerSearchLegacyParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdmissionsControllerSearchLegacySortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * Search query (GR, phone, name, father name)
   */
  query: string;
  /**
   * Sort by
   */
  sortBy?: AdmissionsControllerSearchLegacySortBy;
};

export type AdmissionsControllerSearchLegacySortOrder =
  (typeof AdmissionsControllerSearchLegacySortOrder)[keyof typeof AdmissionsControllerSearchLegacySortOrder];

export const AdmissionsControllerSearchLegacySortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdmissionsControllerSearchLegacySortBy =
  (typeof AdmissionsControllerSearchLegacySortBy)[keyof typeof AdmissionsControllerSearchLegacySortBy];

export const AdmissionsControllerSearchLegacySortBy = {
  grNo: 'grNo',
  name: 'name',
  fathersName: 'fathersName',
  phoneNumber: 'phoneNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AdmissionsControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdmissionsControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * sessionId
   */
  sessionId?: string;
  /**
   * branchId
   */
  branchId?: string;
  /**
   * areaId
   */
  areaId?: string;
  /**
   * grNumber (exact match)
   */
  grNumber?: string;
  /**
   * name (contains)
   */
  name?: string;
  /**
   * fatherName (contains)
   */
  fatherName?: string;
  /**
   * phone (contains)
   */
  phone?: string;
  /**
   * schoolName (contains)
   */
  schoolName?: string;
  /**
   * classLevelId
   */
  classLevelId?: string;
  /**
   * classLevelGroup
   */
  classLevelGroup?: ClassLevelGroup;
  status?: AdmissionsControllerFindAllStatus;
  /**
   * isFeePaid
   */
  isFeePaid?: boolean;
  /**
   * Sort by
   */
  sortBy?: AdmissionsControllerFindAllSortBy;
  /**
   * One search to query all fields
   */
  search?: string;
};

export type AdmissionsControllerFindAllSortOrder =
  (typeof AdmissionsControllerFindAllSortOrder)[keyof typeof AdmissionsControllerFindAllSortOrder];

export const AdmissionsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdmissionsControllerFindAllStatus =
  (typeof AdmissionsControllerFindAllStatus)[keyof typeof AdmissionsControllerFindAllStatus];

export const AdmissionsControllerFindAllStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export type AdmissionsControllerFindAllSortBy =
  (typeof AdmissionsControllerFindAllSortBy)[keyof typeof AdmissionsControllerFindAllSortBy];

export const AdmissionsControllerFindAllSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  isFeePaid: 'isFeePaid',
} as const;

export type AdmissionsControllerGetDashboardParams = {
  /**
   * Filter statistics by a specific session ID. If omitted, aggregates across all sessions.
   */
  sessionId?: string;
  /**
   * Filter statistics by a specific branch ID. If omitted, aggregates across all branches.
   */
  branchId?: string;
  /**
   * Number of days for the recent trend time series (recentTrend). The API returns a day-by-day series from (today - days + 1) to today. Useful for rendering admission/interaction charts.
   * @minimum 1
   * @maximum 365
   */
  days?: number;
};

export type AdmissionsControllerFindOneParams = {
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
};

export type InteractionsControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: InteractionsControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * Session ID (required for listing)
   */
  sessionId?: string;
  /**
   * Branch ID
   */
  branchId?: string;
  /**
   * Area ID
   */
  areaId?: string;
  /**
   * Class Level ID
   */
  classLevelId?: string;
  /**
   * Teacher ID (who conducted the interaction)
   */
  teacherId?: string;
  /**
   * GR Number (contains)
   */
  grNumber?: string;
  /**
   * Student name (contains)
   */
  name?: string;
  /**
   * Father name (contains)
   */
  fatherName?: string;
  /**
   * Filter by gender
   */
  gender?: InteractionsControllerFindAllGender;
  /**
   * One search to query grNumber, name, phone
   */
  search?: string;
  /**
   * Include inactive admissions
   */
  includeInactive?: boolean;
  /**
   * Sort by
   */
  sortBy?: InteractionsControllerFindAllSortBy;
};

export type InteractionsControllerFindAllSortOrder =
  (typeof InteractionsControllerFindAllSortOrder)[keyof typeof InteractionsControllerFindAllSortOrder];

export const InteractionsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type InteractionsControllerFindAllGender =
  (typeof InteractionsControllerFindAllGender)[keyof typeof InteractionsControllerFindAllGender];

export const InteractionsControllerFindAllGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export type InteractionsControllerFindAllSortBy =
  (typeof InteractionsControllerFindAllSortBy)[keyof typeof InteractionsControllerFindAllSortBy];

export const InteractionsControllerFindAllSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type InteractionsControllerGetDashboardParams = {
  /**
   * Session ID (required)
   */
  sessionId: string;
  /**
   * Class Level ID (required)
   */
  classLevelId: string;
  /**
   * Branch ID (required)
   */
  branchId: string;
  /**
   * Area ID (optional filter)
   */
  areaId?: string;
};

export type QuestionSetControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: QuestionSetControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * sessionId
   */
  sessionId?: string;
  /**
   * classLevelId
   */
  classLevelId?: string;
  /**
   * title (contains)
   */
  title?: string;
  /**
   * Sort by
   */
  sortBy?: QuestionSetControllerFindAllSortBy;
};

export type QuestionSetControllerFindAllSortOrder =
  (typeof QuestionSetControllerFindAllSortOrder)[keyof typeof QuestionSetControllerFindAllSortOrder];

export const QuestionSetControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type QuestionSetControllerFindAllSortBy =
  (typeof QuestionSetControllerFindAllSortBy)[keyof typeof QuestionSetControllerFindAllSortBy];

export const QuestionSetControllerFindAllSortBy = {
  id: 'id',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type QuestionSetControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type LegacyStudentImportControllerFindAllParams = {
  /**
   * Skip records for pagination
   */
  skip?: number;
  /**
   * Take records for pagination
   */
  take?: number;
  /**
   * Search by name
   */
  name?: string;
  /**
   * Search by father's name
   */
  fathersName?: string;
  /**
   * Search by phone number
   */
  phoneNumber?: string;
  /**
   * Search by GR number
   */
  grNo?: string;
};

export type PrintingControllerPreviewIdCardsParams = {
  /**
   * Specific admission IDs to generate cards for. When provided, other filters are ignored.
   */
  admissionIds?: string[];
  /**
   * Session ID (required when admissionIds is not provided)
   */
  sessionId: string;
  /**
   * Branch ID
   */
  branchId?: string;
  /**
   * Area ID
   */
  areaId?: string;
  /**
   * Van ID (filters via area-van relationship)
   */
  vanId?: string;
  /**
   * Class Level ID
   */
  classLevelId?: string;
  /**
   * Class Level Group
   */
  classLevelGroup?: string;
  /**
   * Admission status filter
   */
  status?: PrintingControllerPreviewIdCardsStatus;
  /**
   * Fee paid status
   */
  isFeePaid?: boolean;
  /**
   * Finalization status
   */
  isFinalized?: boolean;
  /**
   * Gender filter
   */
  gender?: PrintingControllerPreviewIdCardsGender;
};

export type PrintingControllerPreviewIdCardsStatus =
  (typeof PrintingControllerPreviewIdCardsStatus)[keyof typeof PrintingControllerPreviewIdCardsStatus];

export const PrintingControllerPreviewIdCardsStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export type PrintingControllerPreviewIdCardsGender =
  (typeof PrintingControllerPreviewIdCardsGender)[keyof typeof PrintingControllerPreviewIdCardsGender];

export const PrintingControllerPreviewIdCardsGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export type PrintingControllerPreviewSittingSlipsParams = {
  /**
   * Specific admission IDs to generate slips for. When provided, other filters are ignored.
   */
  admissionIds?: string[];
  /**
   * Session ID (required when admissionIds is not provided)
   */
  sessionId: string;
  /**
   * Branch ID
   */
  branchId?: string;
  /**
   * Area ID
   */
  areaId?: string;
  /**
   * Gender filter
   */
  gender?: PrintingControllerPreviewSittingSlipsGender;
};

export type PrintingControllerPreviewSittingSlipsGender =
  (typeof PrintingControllerPreviewSittingSlipsGender)[keyof typeof PrintingControllerPreviewSittingSlipsGender];

export const PrintingControllerPreviewSittingSlipsGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export type PrintingControllerPreviewAttendanceSheetsParams = {
  /**
   * Session ID (required)
   */
  sessionId: string;
  /**
   * Area ID (required - generates per area)
   */
  areaId: string;
  /**
   * Gender filter
   */
  gender?: PrintingControllerPreviewAttendanceSheetsGender;
  /**
   * Class level groups to include (default: MUHIBAN, NASIRAN)
   */
  classLevelGroups?: ClassLevelGroup[];
};

export type PrintingControllerPreviewAttendanceSheetsGender =
  (typeof PrintingControllerPreviewAttendanceSheetsGender)[keyof typeof PrintingControllerPreviewAttendanceSheetsGender];

export const PrintingControllerPreviewAttendanceSheetsGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export type PrintingControllerListCardPrintRequestsParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: PrintingControllerListCardPrintRequestsSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * Session ID (required)
   */
  sessionId: string;
  /**
   * Branch ID filter
   */
  branchId?: string;
  /**
   * Status filter
   */
  status?: PrintingControllerListCardPrintRequestsStatus;
};

export type PrintingControllerListCardPrintRequestsSortOrder =
  (typeof PrintingControllerListCardPrintRequestsSortOrder)[keyof typeof PrintingControllerListCardPrintRequestsSortOrder];

export const PrintingControllerListCardPrintRequestsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type PrintingControllerListCardPrintRequestsStatus =
  (typeof PrintingControllerListCardPrintRequestsStatus)[keyof typeof PrintingControllerListCardPrintRequestsStatus];

export const PrintingControllerListCardPrintRequestsStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type PrintingControllerCountCardPrintRequestsParams = {
  /**
   * Session ID (required)
   */
  sessionId: string;
  /**
   * Branch ID filter
   */
  branchId?: string;
  /**
   * Status filter
   */
  status?: PrintingControllerCountCardPrintRequestsStatus;
};

export type PrintingControllerCountCardPrintRequestsStatus =
  (typeof PrintingControllerCountCardPrintRequestsStatus)[keyof typeof PrintingControllerCountCardPrintRequestsStatus];

export const PrintingControllerCountCardPrintRequestsStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
