/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
export interface AssetDetailResponseDto {
  id: string;
  title: string;
  mimeType: string;
  /** Short-lived signed URL */
  signedUrl: string;
  /** Expiry in seconds */
  expiresIn: number;
}

export interface UploadFileRequestDto {
  /** File to upload */
  file: Blob;
}

export interface AssetUploadResponseDto {
  id: string;
}

export interface AssetDeleteResponseDto {
  /** Message of the action */
  message: string;
}

export interface AdminLoginRequestDto {
  /** Admin email address */
  email: string;
  /**
   * Admin password
   * @minLength 6
   */
  password: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminLoginResponseDto {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** Token expiration time */
  expiresIn: number;
  /** Whether the user needs to change their temporary password */
  requiresPasswordChange: boolean;
}

export interface AdminLoginFirebaseRequestDto {
  /** Firebase ID token */
  idToken: string;
}

export interface AdminRefreshRequestDto {
  /** JWT refresh token */
  refreshToken: string;
}

export interface AdminRefreshResponseDto {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** Token expiration time */
  expiresIn: number;
  /** Whether the user needs to change their temporary password */
  requiresPasswordChange: boolean;
}

export interface AdminUser {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
  /** The role of the admin user */
  role: string;
  /** Whether the admin user is active */
  isActive: boolean;
  /** Whether the admin user is forced to change their password */
  forcePasswordChange: boolean;
  /** Count of consecutive failed login attempts */
  failedLoginAttempts: number;
  /** Whether login is disabled due to failed attempts */
  isLoginDisabled: boolean;
  /** When the admin user was created */
  createdAt: string;
  /** When the admin user was last updated */
  updatedAt?: string;
  /** The temporary password of the admin user, used for initial login */
  tempPassword?: string;
}

export interface AdminDetailResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface AdminEnableLoginRequestDto {
  /** Admin user id to re-enable login for */
  adminUserId: string;
}

export interface AdminEnableLoginResponseDto {
  /** Message of the action */
  message: string;
}

export interface CreateAdminUserDto {
  /** Admin name */
  name: string;
  /** Admin email address */
  email: string;
}

export interface CreateAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface ListAdminUsersResponseDto {
  /** Total number of records */
  count: number;
  data: AdminUser[];
}

export interface DetailAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface UpdateAdminUserDto {
  /** Admin name */
  name?: string;
  /** Admin email address */
  email?: string;
}

export interface UpdateAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface ActionResponseDto {
  /** Message of the action */
  message: string;
}

export interface AdminChangePasswordRequestDto {
  /** Current password */
  currentPassword: string;
  /** New password */
  newPassword: string;
}

export interface AdminChangePasswordResponseDto {
  /** Success message */
  message: string;
}

export interface AdminForgotPasswordRequestDto {
  /** Admin email address */
  email: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminForgotPasswordResponseDto {
  /** Success message */
  message: string;
  /** Reset token */
  token: string;
}

export interface AdminResetPasswordRequestDto {
  /** Reset token received via email */
  token: string;
  /** New password */
  newPassword: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminResetPasswordResponseDto {
  /** Success message */
  message: string;
}

export interface AdminCreatePasswordRequestDto {
  /** New password to replace temporary password */
  newPassword: string;
}

export interface AdminCreatePasswordResponseDto {
  /** Success message */
  message: string;
}

export interface CreateAclRequestDto {
  key: string;
  value: string;
  description?: string;
  isPublic?: boolean;
}

export interface Acl {
  /** Whether the category is active */
  isActive: boolean;
  /** Created at timestamp */
  createdAt: string;
  /** Last updated timestamp */
  updatedAt?: string;
  id: number;
  key: string;
  value: string;
  description?: string;
}

export interface CreateAclResponseDto {
  message: string;
  data: Acl;
}

export interface ExtendedAcl {
  /** Whether the category is active */
  isActive: boolean;
  /** Created at timestamp */
  createdAt: string;
  /** Last updated timestamp */
  updatedAt?: string;
  id: number;
  key: string;
  value: string;
  description?: string;
}

export interface ListAclResponseDto {
  /** Total number of records */
  count: number;
  data: ExtendedAcl[];
}

export interface DetailAclResponseDto {
  data: ExtendedAcl;
}

export interface UpdateAclRequestDto {
  key: string;
  value?: string;
  description?: string;
}

export interface UpdateAclResponseDto {
  message: string;
  data: Acl;
}

export interface CreateBranchDto {
  /** code */
  code: string;
  /** name */
  name: string;
  /** defaultColorName */
  defaultColorName?: string;
  /** defaultColorHex (e.g. #FF5733) */
  defaultColorHex?: string;
}

export interface AdminUserBase {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
}

export interface Branch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** defaultColorName */
  defaultColorName?: string;
  /** defaultColorHex */
  defaultColorHex?: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateBranchResponseDto {
  /** Message of the action */
  message: string;
  data: Branch;
}

export interface ListBranchesResponseDto {
  /** Total number of records */
  count: number;
  data: Branch[];
}

export interface DetailBranchesResponseDto {
  /** Message of the action */
  message: string;
  data: Branch;
}

export interface UpdateBranchDto {
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** defaultColorName */
  defaultColorName?: string;
  /** defaultColorHex (e.g. #FF5733) */
  defaultColorHex?: string;
}

export interface UpdateBranchResponseDto {
  /** Message of the action */
  message: string;
  data?: Branch;
}

export interface CreateAreaDto {
  /** branchId */
  branchId: string;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan?: boolean;
  /** hasBoysVan */
  hasBoysVan?: boolean;
}

export interface AreaBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface Area {
  /** id */
  id: string;
  /** branch */
  branch: AreaBranch;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan: boolean;
  /** hasBoysVan */
  hasBoysVan: boolean;
  /** lastYearTotal */
  lastYearTotal: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateAreaResponseDto {
  /** Message of the action */
  message: string;
  data: Area;
}

export interface ListAreasResponseDto {
  /** Total number of records */
  count: number;
  data: Area[];
}

export interface DetailAreasResponseDto {
  /** Message of the action */
  message: string;
  data: Area;
}

export interface UpdateAreaDto {
  /** branchId */
  branchId?: string;
  /** alias */
  alias?: string;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** hasVan */
  hasVan?: boolean;
  /** hasBoysVan */
  hasBoysVan?: boolean;
}

export interface UpdateAreaResponseDto {
  /** Message of the action */
  message: string;
  data?: Area;
}

export interface CreateVanDto {
  /** branchId */
  branchId: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** colorName */
  colorName: string;
  /** colorHex (e.g. #FF5733) */
  colorHex: string;
  /** areaIds */
  areaIds?: string[];
}

export interface VanBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface VanArea {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** alias */
  alias: string;
}

export interface Van {
  /** id */
  id: string;
  /** branch */
  branch: VanBranch;
  /** code */
  code: string;
  /** name */
  name: string;
  /** colorName */
  colorName: string;
  /** colorHex */
  colorHex: string;
  /** areas */
  areas?: VanArea[];
  /** Male confirmed count (fees paid) */
  maleConfirmedCount?: number;
  /** Male applied count (fees not paid) */
  maleAppliedCount?: number;
  /** Female confirmed count (fees paid) */
  femaleConfirmedCount?: number;
  /** Female applied count (fees not paid) */
  femaleAppliedCount?: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateVanResponseDto {
  /** Message of the action */
  message: string;
  data: Van;
}

export interface ListVansResponseDto {
  /** Total number of records */
  count: number;
  data: Van[];
}

export interface DetailVansResponseDto {
  /** Message of the action */
  message: string;
  data: Van;
}

export interface UpdateVanDto {
  /** branchId */
  branchId?: string;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** colorName */
  colorName?: string;
  /** colorHex (e.g. #FF5733) */
  colorHex?: string;
  /** areaIds - replaces all existing area associations */
  areaIds?: string[];
}

export interface UpdateVanResponseDto {
  /** Message of the action */
  message: string;
  data?: Van;
}

export interface CreateSessionDto {
  /** name */
  name: string;
  /** attendanceDays */
  attendanceDays?: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
}

export interface Session {
  /** id */
  id: string;
  /** name */
  name: string;
  /** attendanceDays */
  attendanceDays: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateSessionResponseDto {
  /** Message of the action */
  message: string;
  data: Session;
}

export interface ListSessionsResponseDto {
  /** Total number of records */
  count: number;
  data: Session[];
}

export interface DetailSessionsResponseDto {
  /** Message of the action */
  message: string;
  data: Session;
}

export interface UpdateSessionDto {
  /** name */
  name?: string;
  /** attendanceDays */
  attendanceDays?: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
}

export interface UpdateSessionResponseDto {
  /** Message of the action */
  message: string;
  data?: Session;
}

export interface AttendanceDay {
  /** id */
  id: string;
  /** sessionId */
  sessionId: string;
  /** date */
  date: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface ListAttendanceDaysResponseDto {
  /** Total number of records */
  count: number;
  data: AttendanceDay[];
}

export type BulkAttendanceRecordItemDtoStatus =
  (typeof BulkAttendanceRecordItemDtoStatus)[keyof typeof BulkAttendanceRecordItemDtoStatus];

export const BulkAttendanceRecordItemDtoStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface BulkAttendanceRecordItemDto {
  /** admissionId */
  admissionId: string;
  status: BulkAttendanceRecordItemDtoStatus;
}

export interface BulkUpsertAttendanceRecordsDto {
  records: BulkAttendanceRecordItemDto[];
}

export interface BulkUpsertAttendanceRecordsResponseDto {
  /** Message of the action */
  message: string;
}

export type AttendanceSummaryRowStatus = (typeof AttendanceSummaryRowStatus)[keyof typeof AttendanceSummaryRowStatus];

export const AttendanceSummaryRowStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface AttendanceSummaryRow {
  /** classLevelId */
  classLevelId: string;
  status: AttendanceSummaryRowStatus;
  /** count */
  count: number;
}

export interface AttendanceSummaryResponseDto {
  /** Message of the action */
  message: string;
  data: AttendanceSummaryRow[];
}

export type StudentAttendanceHistoryRowStatus =
  (typeof StudentAttendanceHistoryRowStatus)[keyof typeof StudentAttendanceHistoryRowStatus];

export const StudentAttendanceHistoryRowStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface StudentAttendanceHistoryRow {
  /** attendanceDayId */
  attendanceDayId: string;
  /** date */
  date: string;
  status: StudentAttendanceHistoryRowStatus;
}

export interface StudentAttendanceHistoryResponseDto {
  /** Message of the action */
  message: string;
  data: StudentAttendanceHistoryRow[];
}

/**
 * group
 */
export type CreateClassLevelDtoGroup = (typeof CreateClassLevelDtoGroup)[keyof typeof CreateClassLevelDtoGroup];

export const CreateClassLevelDtoGroup = {
  TIFLAN: 'TIFLAN',
  MUHIBAN: 'MUHIBAN',
  NASIRAN: 'NASIRAN',
} as const;

/**
 * gender
 */
export type CreateClassLevelDtoGender = (typeof CreateClassLevelDtoGender)[keyof typeof CreateClassLevelDtoGender];

export const CreateClassLevelDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface CreateClassLevelDto {
  /** group */
  group: CreateClassLevelDtoGroup;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: CreateClassLevelDtoGender;
  /** sortOrder */
  sortOrder?: number;
}

/**
 * group
 */
export type ClassLevelGroup = (typeof ClassLevelGroup)[keyof typeof ClassLevelGroup];

export const ClassLevelGroup = {
  TIFLAN: 'TIFLAN',
  MUHIBAN: 'MUHIBAN',
  NASIRAN: 'NASIRAN',
} as const;

/**
 * gender
 */
export type ClassLevelGender = (typeof ClassLevelGender)[keyof typeof ClassLevelGender];

export const ClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface ClassLevel {
  /** group */
  group: ClassLevelGroup;
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: ClassLevelGender;
  /** sortOrder */
  sortOrder: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateClassLevelResponseDto {
  /** Message of the action */
  message: string;
  data: ClassLevel;
}

export interface ListClassLevelsResponseDto {
  /** Total number of records */
  count: number;
  data: ClassLevel[];
}

export interface DetailClassLevelsResponseDto {
  /** Message of the action */
  message: string;
  data: ClassLevel;
}

/**
 * group
 */
export type UpdateClassLevelDtoGroup = (typeof UpdateClassLevelDtoGroup)[keyof typeof UpdateClassLevelDtoGroup];

export const UpdateClassLevelDtoGroup = {
  TIFLAN: 'TIFLAN',
  MUHIBAN: 'MUHIBAN',
  NASIRAN: 'NASIRAN',
} as const;

/**
 * gender
 */
export type UpdateClassLevelDtoGender = (typeof UpdateClassLevelDtoGender)[keyof typeof UpdateClassLevelDtoGender];

export const UpdateClassLevelDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface UpdateClassLevelDto {
  /** group */
  group?: UpdateClassLevelDtoGroup;
  /** age */
  age?: number;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** gender */
  gender?: UpdateClassLevelDtoGender;
  /** sortOrder */
  sortOrder?: number;
}

export interface UpdateClassLevelResponseDto {
  /** Message of the action */
  message: string;
  data?: ClassLevel;
}

/**
 * normalized gender (if possible)
 */
export type LegacyAdmissionPrefillGender =
  (typeof LegacyAdmissionPrefillGender)[keyof typeof LegacyAdmissionPrefillGender];

export const LegacyAdmissionPrefillGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface LegacyAdmissionPrefill {
  /** legacyStudentId */
  legacyStudentId?: string;
  /** branchId (auto-resolved if possible) */
  branchId?: string;
  /** areaId (auto-resolved if possible) */
  areaId?: string;
  /** student name */
  name?: string;
  /** father/guardian name */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  /** normalized gender (if possible) */
  gender?: LegacyAdmissionPrefillGender;
  /** phone */
  phone?: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber (B-Form/CNIC as text) */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
}

export interface LegacyAdmissionRaw {
  /** legacy grNo */
  grNo?: string;
  /** legacy area code (string) */
  area?: string;
  /** legacy city */
  city?: string;
  /** legacy imageUrl */
  imageUrl?: string;
}

export interface LegacyStudentRow {
  /** id */
  id: string;
  /** true if an admission already exists for this phone */
  alreadyRegistered: boolean;
  /** grNumber (legacy gr_no) */
  grNumber?: string;
  /** name */
  name?: string;
  /** fatherName (legacy fathers_name) */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  /** gender (legacy free-form text) */
  gender?: string;
  /** phone */
  phone?: string;
  /** identityNumber (legacy b_form_or_birth_certificate_no) */
  identityNumber?: string;
  /** isVerified */
  isVerified?: boolean;
  /** prefill payload for admission create form */
  prefill: LegacyAdmissionPrefill;
  /** warnings produced while building prefill */
  warnings: string[];
  /** raw legacy fields for display/debug */
  raw: LegacyAdmissionRaw;
}

export interface SearchLegacyAdmissionsResponseDto {
  /** Total number of records */
  count: number;
  data: LegacyStudentRow[];
}

export type CreateAdmissionDtoGender = (typeof CreateAdmissionDtoGender)[keyof typeof CreateAdmissionDtoGender];

export const CreateAdmissionDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface CreateAdmissionDto {
  /** sessionId */
  sessionId: string;
  /** legacyStudentId (optional for legacy prefill) */
  legacyStudentId?: string;
  /** branchId */
  branchId: string;
  /** areaId */
  areaId: string;
  /** student name */
  name: string;
  /** father/guardian name */
  fatherName: string;
  /** dateOfBirth */
  dateOfBirth: string;
  gender: CreateAdmissionDtoGender;
  /** phone */
  phone: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber (B-Form/CNIC as text) */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface AdmissionSession {
  /** id */
  id: string;
  /** name */
  name: string;
}

export type AdmissionStudentGender = (typeof AdmissionStudentGender)[keyof typeof AdmissionStudentGender];

export const AdmissionStudentGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionStudent {
  /** id */
  id: string;
  /** grNumber */
  grNumber: string;
  /** name */
  name: string;
  /** fatherName */
  fatherName: string;
  /** dateOfBirth */
  dateOfBirth: string;
  gender: AdmissionStudentGender;
  /** phone */
  phone: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber */
  identityNumber?: string;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface AdmissionInteractionTeacher {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
}

export interface AdmissionInteractionQuestionSet {
  /** id */
  id: string;
  /** title */
  title: string;
}

export interface AdmissionInteractionQuestion {
  /** id */
  id: string;
  /** prompt */
  prompt: string;
  /** sortOrder */
  sortOrder: number;
}

export interface AdmissionInteractionRating {
  /** id */
  id: string;
  /** rating */
  rating: number;
  /** notes */
  notes?: string;
  /** question */
  question: AdmissionInteractionQuestion;
}

export interface AdmissionInteraction {
  /** id */
  id: string;
  /** notes */
  notes?: string;
  /** teacher */
  teacher: AdmissionInteractionTeacher;
  /** questionSet */
  questionSet: AdmissionInteractionQuestionSet;
  /** ratings */
  ratings: AdmissionInteractionRating[];
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface AdmissionBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface AdmissionArea {
  /** id */
  id: string;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan: boolean;
  /** hasBoysVan */
  hasBoysVan: boolean;
}

/**
 * gender
 */
export type AdmissionClassLevelGender = (typeof AdmissionClassLevelGender)[keyof typeof AdmissionClassLevelGender];

export const AdmissionClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionClassLevel {
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: AdmissionClassLevelGender;
}

export type AdmissionStatus = (typeof AdmissionStatus)[keyof typeof AdmissionStatus];

export const AdmissionStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface Admission {
  /** id */
  id: string;
  status: AdmissionStatus;
  /** rejectedReason */
  rejectedReason?: string;
  /** session */
  session: AdmissionSession;
  /** student */
  student: AdmissionStudent;
  /** interaction */
  interaction?: AdmissionInteraction;
  /** branch */
  branch: AdmissionBranch;
  /** area */
  area: AdmissionArea;
  /** classLevel */
  classLevel: AdmissionClassLevel;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired: boolean;
  /** isMarried */
  isMarried: boolean;
  /** isWorking */
  isWorking: boolean;
  /** isFinalized */
  isFinalized: boolean;
  /** finalizedAt */
  finalizedAt?: string;
  /** finalizedByAdmin */
  finalizedByAdmin?: AdminUserBase;
  /** isFeePaid */
  isFeePaid: boolean;
  /** feePaidAt */
  feePaidAt?: string;
  /** feePaidByAdmin */
  feePaidByAdmin?: AdminUserBase;
  /** legacyStudentId */
  legacyStudentId?: string;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface CreateAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface ListAdmissionsResponseDto {
  /** Total number of records */
  count: number;
  data: Admission[];
}

/**
 * Admission status (UNVERIFIED, VERIFIED, REJECTED)
 */
export type AdmissionsDashboardStatusStatStatus =
  (typeof AdmissionsDashboardStatusStatStatus)[keyof typeof AdmissionsDashboardStatusStatStatus];

export const AdmissionsDashboardStatusStatStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface AdmissionsDashboardStatusStat {
  /** Admission status (UNVERIFIED, VERIFIED, REJECTED) */
  status: AdmissionsDashboardStatusStatStatus;
  /** Number of admissions in this status */
  count: number;
}

/**
 * Student gender (MALE, FEMALE)
 */
export type AdmissionsDashboardGenderStatGender =
  (typeof AdmissionsDashboardGenderStatGender)[keyof typeof AdmissionsDashboardGenderStatGender];

export const AdmissionsDashboardGenderStatGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionsDashboardGenderStat {
  /** Student gender (MALE, FEMALE) */
  gender: AdmissionsDashboardGenderStatGender;
  /** Number of admissions for this gender */
  count: number;
}

/**
 * Gender this class level is designated for
 */
export type AdmissionsDashboardClassLevelStatGender =
  (typeof AdmissionsDashboardClassLevelStatGender)[keyof typeof AdmissionsDashboardClassLevelStatGender];

export const AdmissionsDashboardClassLevelStatGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionsDashboardClassLevelStat {
  /** Class level code (e.g., "KG", "1", "2") */
  code: string;
  /** Class level display name (e.g., "Kindergarten", "Grade 1") */
  name: string;
  /** Gender this class level is designated for */
  gender: AdmissionsDashboardClassLevelStatGender;
  /** Number of admissions in this class level */
  count: number;
}

export interface AdmissionsDashboardAreaStat {
  /** Area ID */
  id: string;
  /** Area name */
  name: string;
  /** Number of admissions this year (current session) */
  thisYear: number;
  /** Number of admissions from last year (stored in area.lastYearTotal) */
  lastYear: number;
  /** Year-over-year growth percentage formatted as string (e.g., "120.00%") */
  percentage: string;
}

/**
 * Class level group category
 */
export type AdmissionsDashboardGroupStatGroup =
  (typeof AdmissionsDashboardGroupStatGroup)[keyof typeof AdmissionsDashboardGroupStatGroup];

export const AdmissionsDashboardGroupStatGroup = {
  TIFLAN: 'TIFLAN',
  MUHIBAN: 'MUHIBAN',
  NASIRAN: 'NASIRAN',
} as const;

export interface AdmissionsDashboardGroupStat {
  /** Class level group category */
  group: AdmissionsDashboardGroupStatGroup;
  /** Number of male students in this group */
  maleCount: number;
  /** Number of female students in this group */
  femaleCount: number;
  /** Total students in this group (maleCount + femaleCount) */
  totalStudents: number;
}

export interface AdmissionsDashboardClassGenderStat {
  /** Class level code (e.g., "KG", "1", "2") */
  code: string;
  /** Class level display name (e.g., "Kindergarten", "Grade 1") */
  name: string;
  /** Number of male students in this class level */
  maleCount: number;
  /** Number of female students in this class level */
  femaleCount: number;
  /** Total students in this class level (maleCount + femaleCount) */
  totalStudents: number;
}

export interface AdmissionsDashboardClassFeeStats {
  /** Class level code (e.g., "KG", "1", "2") */
  code: string;
  /** Class level display name (e.g., "Kindergarten", "Grade 1") */
  name: string;
  /** Number of students who have paid fee in this class level */
  feePaidCount: number;
  /** Number of students who have not paid fee in this class level */
  feeNotPaidCount: number;
  /** Total students in this class level */
  totalStudents: number;
}

export interface FeeCardClassStat {
  /** Class level code (e.g., "Tiflan1", "Muhiban5") */
  code: string;
  /** Class level display name */
  name: string;
  /** Total admissions (expected) */
  expected: number;
  /** Fee paid admissions (confirmed) */
  confirmed: number;
}

export interface FeeCardTotal {
  /** Total expected admissions */
  expected: number;
  /** Total confirmed (fee paid) admissions */
  confirmed: number;
}

export interface TiflanFeeCard {
  /** Fee stats for each Tiflan class (both genders combined) */
  classes: FeeCardClassStat[];
  /** Total expected and confirmed for Tiflan */
  total: FeeCardTotal;
}

export interface MuhibanFeeCard {
  /** Fee stats for each Muhiban class */
  classes: FeeCardClassStat[];
  /** Total expected and confirmed for this Muhiban gender */
  total: FeeCardTotal;
}

/**
 * Student gender
 */
export type FeeCardGenderStatGender = (typeof FeeCardGenderStatGender)[keyof typeof FeeCardGenderStatGender];

export const FeeCardGenderStatGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface FeeCardGenderStat {
  /** Student gender */
  gender: FeeCardGenderStatGender;
  /** Total admissions (expected) */
  expected: number;
  /** Fee paid admissions (confirmed) */
  confirmed: number;
}

export interface NasiranFeeCard {
  /** Fee stats for each gender in Nasiran */
  genders: FeeCardGenderStat[];
  /** Total expected and confirmed for Nasiran */
  total: FeeCardTotal;
}

export interface FeeCardStats {
  /** Tiflan fee card - all classes regardless of gender */
  tiflan: TiflanFeeCard;
  /** Muhiban Boys fee card - boys classes only */
  muhibanBoys: MuhibanFeeCard;
  /** Muhiban Girls fee card - girls classes only */
  muhibanGirls: MuhibanFeeCard;
  /** Nasiran fee card - breakdown by gender */
  nasiran: NasiranFeeCard;
}

export interface AdmissionsDashboardFunnel {
  /** Total number of active admissions */
  totalAdmissions: number;
  /** Number of admissions in UNVERIFIED status (pending document verification) */
  unverified?: number;
  /** Number of admissions in VERIFIED status (documents approved) */
  verified?: number;
  /** Number of admissions in REJECTED status */
  rejected?: number;
  /** Number of admissions where fee has been paid */
  feePaid: number;
  /** Number of admissions that have been finalized (enrollment complete) */
  finalized: number;
  /** Number of admissions where teacher interaction has been submitted */
  interactionSubmitted: number;
  /** Number of VERIFIED admissions that have NOT paid fee yet. Identifies students stuck after verification. */
  verifiedNotFeePaid: number;
  /** Number of fee-paid admissions that have NOT been finalized yet. Identifies students stuck after payment. */
  feePaidNotFinalized: number;
}

export interface AdmissionsDashboardRates {
  /** Percentage of total admissions that have paid fee (0-100, rounded to 2 decimals) */
  feePaidRate: number;
  /** Percentage of total admissions that have been finalized (0-100, rounded to 2 decimals) */
  finalizedRate: number;
  /** Percentage of total admissions that have completed teacher interaction (0-100, rounded to 2 decimals) */
  interactionSubmittedRate: number;
}

export interface AdmissionsDashboardAverages {
  /** Average number of days from admission creation to fee payment. Null if no fee-paid admissions exist. */
  avgDaysToFeePaid?: number;
  /** Average number of days from admission creation to finalization. Null if no finalized admissions exist. */
  avgDaysToFinalized?: number;
}

export interface AdmissionsDashboardTrendPoint {
  /** Date in ISO format (YYYY-MM-DD) */
  date: string;
  /** Number of admissions created on this date */
  admissionsCreated: number;
  /** Number of teacher interactions submitted on this date */
  interactionsSubmitted: number;
}

export interface AdmissionsDashboardResponseData {
  /** Timestamp when this dashboard data was generated */
  generatedAt: string;
  /** Session ID filter applied (if any) */
  sessionId?: string;
  /** Branch ID filter applied (if any) */
  branchId?: string;
  /** Number of days in the recentTrend time series */
  days: number;
  /** Admission counts grouped by status */
  statusStats: AdmissionsDashboardStatusStat[];
  /** Admission counts grouped by student gender */
  genderStats: AdmissionsDashboardGenderStat[];
  /** Admission counts grouped by class level */
  classLevelStats: AdmissionsDashboardClassLevelStat[];
  /** Admission counts grouped by area with year-over-year comparison */
  areaStats: AdmissionsDashboardAreaStat[];
  /** Admission counts grouped by class level group with gender breakdown */
  groupStats: AdmissionsDashboardGroupStat[];
  /** Admission counts grouped by class level (e.g. KG, Grade 1) with male/female breakdown */
  classGenderStats: AdmissionsDashboardClassGenderStat[];
  /** Admission counts grouped by class level (e.g. KG, Grade 1) with fee paid/not paid breakdown */
  classFeeStats: AdmissionsDashboardClassFeeStats[];
  /** Fee card stats for the 4 frontend cards (Tiflan, Muhiban Boys, Muhiban Girls, Nasiran) */
  feeCardStats: FeeCardStats;
  /** Funnel metrics showing admission progression and bottlenecks */
  funnel: AdmissionsDashboardFunnel;
  /** Conversion rate percentages for key milestones */
  rates: AdmissionsDashboardRates;
  /** Average time metrics for admission process steps */
  averages: AdmissionsDashboardAverages;
  /** Day-by-day time series of admissions created and interactions submitted. Includes all days in the range (including zero-count days) for proper chart rendering. */
  recentTrend: AdmissionsDashboardTrendPoint[];
}

export interface AdmissionsDashboardResponseDto {
  /** Message of the action */
  message: string;
  /** Dashboard statistics and metrics */
  data: AdmissionsDashboardResponseData;
}

export interface DetailAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export type UpdateAdmissionDtoGender = (typeof UpdateAdmissionDtoGender)[keyof typeof UpdateAdmissionDtoGender];

export const UpdateAdmissionDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface UpdateAdmissionDto {
  /** branchId */
  branchId?: string;
  /** areaId */
  areaId?: string;
  /** student name */
  name?: string;
  /** father/guardian name */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  gender?: UpdateAdmissionDtoGender;
  /** phone */
  phone?: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** schoolClass */
  schoolClass?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface UpdateAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data?: Admission;
}

export type UpdateAdmissionStatusDtoStatus =
  (typeof UpdateAdmissionStatusDtoStatus)[keyof typeof UpdateAdmissionStatusDtoStatus];

export const UpdateAdmissionStatusDtoStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface UpdateAdmissionStatusDto {
  status: UpdateAdmissionStatusDtoStatus;
  /** rejectedReason (required when status=REJECTED) */
  rejectedReason?: string;
  /** adminUserId (optional, for audit fields) */
  adminUserId?: string;
}

export interface UpdateAdmissionStatusResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface MarkFeePaidDto {
  /** isFeePaid */
  isFeePaid: boolean;
  /** adminUserId (optional, for audit fields) */
  adminUserId?: string;
}

export interface MarkFeePaidResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface FinalizeAdmissionDto {
  /** isFinalized */
  isFinalized: boolean;
  /** adminUserId (optional, for audit fields) */
  adminUserId?: string;
}

export interface FinalizeAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface InteractionTemplateStudent {
  id: string;
  grNumber: string;
  name: string;
  fatherName: string;
}

export interface InteractionTemplateAdmission {
  id: string;
  sessionId: string;
  classLevelId: string;
}

export interface InteractionTemplateQuestionSet {
  id: string;
  title: string;
}

export interface InteractionQuestion {
  /** Question id */
  id: string;
  /** Prompt to display to teacher */
  prompt: string;
  /** Sort order */
  sortOrder: number;
}

export interface InteractionTemplate {
  student: InteractionTemplateStudent;
  admission: InteractionTemplateAdmission;
  questionSet: InteractionTemplateQuestionSet;
  questions: InteractionQuestion[];
}

export interface GetInteractionTemplateResponseDto {
  /** Message of the action */
  message: string;
  data: InteractionTemplate;
}

export interface CreateInteractionRatingDto {
  /** Question id */
  questionId: string;
  /**
   * Rating value (1..5)
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** Optional notes for this question */
  notes?: string;
}

export interface CreateInteractionDto {
  /** Student id (from search / QR) */
  studentId: string;
  /** Overall notes for interaction */
  notes?: string;
  ratings: CreateInteractionRatingDto[];
}

export interface CreateInteractionResponseData {
  id: string;
  admissionId: string;
}

export interface CreateInteractionResponseDto {
  /** Message of the action */
  message: string;
  data: CreateInteractionResponseData;
}

export interface CreateQuestionSetQuestionDto {
  /** prompt */
  prompt: string;
  /** sortOrder (defaults to array index) */
  sortOrder?: number;
}

export interface CreateQuestionSetDto {
  /** sessionId */
  sessionId: string;
  /** classLevelId */
  classLevelId: string;
  /** title */
  title: string;
  /** questions */
  questions: CreateQuestionSetQuestionDto[];
}

export interface QuestionSetSession {
  /** id */
  id: string;
  /** name */
  name: string;
}

/**
 * gender
 */
export type QuestionSetClassLevelGender =
  (typeof QuestionSetClassLevelGender)[keyof typeof QuestionSetClassLevelGender];

export const QuestionSetClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface QuestionSetClassLevel {
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: QuestionSetClassLevelGender;
}

export interface QuestionSetQuestion {
  /** id */
  id: string;
  /** prompt */
  prompt: string;
  /** sortOrder */
  sortOrder: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface QuestionSet {
  /** id */
  id: string;
  /** session */
  session: QuestionSetSession;
  /** classLevel */
  classLevel: QuestionSetClassLevel;
  /** title */
  title: string;
  /** questions */
  questions: QuestionSetQuestion[];
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface CreateQuestionSetResponseDto {
  /** Message of the action */
  message: string;
  data: QuestionSet;
}

export interface ListQuestionSetsResponseDto {
  /** Total number of records */
  count: number;
  data: QuestionSet[];
}

export interface DetailQuestionSetsResponseDto {
  /** Message of the action */
  message: string;
  data: QuestionSet;
}

export interface UpdateQuestionSetDto {
  /** sessionId */
  sessionId?: string;
  /** classLevelId */
  classLevelId?: string;
  /** title */
  title?: string;
  /** Replace all questions when provided (full replacement) */
  questions?: CreateQuestionSetQuestionDto[];
}

export interface UpdateQuestionSetResponseDto {
  /** Message of the action */
  message: string;
  data?: QuestionSet;
}

export interface ImportLegacyStudentsRequestDto {
  /** CSV file to import */
  file: Blob;
}

export interface ImportLegacyStudentsResponseDto {
  /** Message of the action */
  message: string;
  /** Total records processed */
  totalProcessed: number;
  /** Records successfully imported */
  successCount: number;
  /** Records inserted */
  insertedCount?: number;
  /** Records updated */
  updatedCount?: number;
  /** Records skipped (duplicates) */
  skippedCount: number;
  /** Records that failed to import */
  errorCount: number;
  /** Error details */
  errors?: string[];
}

export interface LegacyStudent {
  /** Unique identifier */
  id: string;
  /** Student name */
  name?: string;
  /** Father's name */
  fathersName?: string;
  /** Date of birth */
  dateOfBirth?: string;
  /** Address */
  address?: string;
  /** Area */
  area?: string;
  /** City */
  city?: string;
  /** Is school going */
  isSchoolGoing?: string;
  /** School name */
  schoolName?: string;
  /** School class */
  schoolClass?: string;
  /** Previously attended madressa */
  previouslyAttendedMadressa?: string;
  /** Previously attended year */
  previouslyAttendedYear?: string;
  /** Previously attended class */
  previouslyAttendedClass?: string;
  /** Phone number */
  phoneNumber?: string;
  /** WhatsApp number */
  whatsappNumber?: string;
  /** Gender */
  gender?: string;
  /** Is married */
  isMarried?: string;
  /** Is working */
  isWorking?: string;
  /** Work type */
  workType?: string;
  /** Email address */
  emailAddress?: string;
  /** Is van required */
  isVanRequired?: string;
  /** Is verified */
  isVerified?: boolean;
  /** Card printed */
  cardPrinted?: boolean;
  /** Van stop */
  vanStop?: string;
  /** B-Form or birth certificate number */
  bFormOrBirthCertificateNo?: string;
  /** GR number */
  grNo?: string;
  /** Category */
  category?: string;
  /** Image URL */
  imageUrl?: string;
  /** Is fees paid */
  isFeesPaid?: string;
  /** Updated by */
  updatedBy?: string;
  /** Admission year */
  admissionYear?: string;
  /** Created at */
  createdAt: string;
  /** Updated at */
  updatedAt?: string;
}

export interface ListLegacyStudentsResponseDto {
  /** Total count */
  count: number;
  /** List of legacy students */
  data: LegacyStudent[];
}

export interface ClearLegacyStudentsRequestDto {
  /** Confirm deletion */
  confirm: boolean;
}

export interface ClearLegacyStudentsResponseDto {
  /** Message of the action */
  message: string;
  /** Number of records deleted */
  deletedCount: number;
}

export type AssetsControllerUploadPublicParams = {
  type: AssetsControllerUploadPublicType;
  /**
   * Category of the asset
   */
  category: string;
};

export type AssetsControllerUploadPublicType =
  (typeof AssetsControllerUploadPublicType)[keyof typeof AssetsControllerUploadPublicType];

export const AssetsControllerUploadPublicType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
} as const;

export type AdminUsersControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdminUsersControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * Email of the admin user
   */
  email?: string;
  /**
   * Name of the admin user
   */
  name?: string;
  /**
   * Sort by
   */
  sortBy?: AdminUsersControllerFindAllSortBy;
};

export type AdminUsersControllerFindAllSortOrder =
  (typeof AdminUsersControllerFindAllSortOrder)[keyof typeof AdminUsersControllerFindAllSortOrder];

export const AdminUsersControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdminUsersControllerFindAllSortBy =
  (typeof AdminUsersControllerFindAllSortBy)[keyof typeof AdminUsersControllerFindAllSortBy];

export const AdminUsersControllerFindAllSortBy = {
  id: 'id',
  name: 'name',
  email: 'email',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AclControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AclControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  key?: string;
  value?: string;
  id?: number;
  sortBy?: AclControllerFindAllSortBy;
  /**
   * Include non-public records
   */
  includeNonPublic?: boolean;
};

export type AclControllerFindAllSortOrder =
  (typeof AclControllerFindAllSortOrder)[keyof typeof AclControllerFindAllSortOrder];

export const AclControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AclControllerFindAllSortBy = (typeof AclControllerFindAllSortBy)[keyof typeof AclControllerFindAllSortBy];

export const AclControllerFindAllSortBy = {
  id: 'id',
  key: 'key',
  value: 'value',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type BranchControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: BranchControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * Sort by
   */
  sortBy?: BranchControllerFindAllSortBy;
};

export type BranchControllerFindAllSortOrder =
  (typeof BranchControllerFindAllSortOrder)[keyof typeof BranchControllerFindAllSortOrder];

export const BranchControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type BranchControllerFindAllSortBy =
  (typeof BranchControllerFindAllSortBy)[keyof typeof BranchControllerFindAllSortBy];

export const BranchControllerFindAllSortBy = {
  id: 'id',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type BranchControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AreaControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AreaControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * branchId
   */
  branchId?: string;
  /**
   * alias
   */
  alias?: string;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * hasVan
   */
  hasVan?: boolean;
  /**
   * hasBoysVan
   */
  hasBoysVan?: boolean;
  /**
   * Sort by
   */
  sortBy?: AreaControllerFindAllSortBy;
};

export type AreaControllerFindAllSortOrder =
  (typeof AreaControllerFindAllSortOrder)[keyof typeof AreaControllerFindAllSortOrder];

export const AreaControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AreaControllerFindAllSortBy =
  (typeof AreaControllerFindAllSortBy)[keyof typeof AreaControllerFindAllSortBy];

export const AreaControllerFindAllSortBy = {
  id: 'id',
  branchId: 'branchId',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AreaControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type VanControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: VanControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * branchId
   */
  branchId?: string;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * sessionId - Filter admission counts by session
   */
  sessionId?: string;
  /**
   * Sort by
   */
  sortBy?: VanControllerFindAllSortBy;
};

export type VanControllerFindAllSortOrder =
  (typeof VanControllerFindAllSortOrder)[keyof typeof VanControllerFindAllSortOrder];

export const VanControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type VanControllerFindAllSortBy = (typeof VanControllerFindAllSortBy)[keyof typeof VanControllerFindAllSortBy];

export const VanControllerFindAllSortBy = {
  id: 'id',
  branchId: 'branchId',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type VanControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type SessionControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: SessionControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * name
   */
  name?: string;
  /**
   * Sort by
   */
  sortBy?: SessionControllerFindAllSortBy;
};

export type SessionControllerFindAllSortOrder =
  (typeof SessionControllerFindAllSortOrder)[keyof typeof SessionControllerFindAllSortOrder];

export const SessionControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type SessionControllerFindAllSortBy =
  (typeof SessionControllerFindAllSortBy)[keyof typeof SessionControllerFindAllSortBy];

export const SessionControllerFindAllSortBy = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type SessionControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AttendanceControllerListDaysParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AttendanceControllerListDaysSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * sessionId
   */
  sessionId: string;
  /**
   * Sort by
   */
  sortBy?: AttendanceControllerListDaysSortBy;
};

export type AttendanceControllerListDaysSortOrder =
  (typeof AttendanceControllerListDaysSortOrder)[keyof typeof AttendanceControllerListDaysSortOrder];

export const AttendanceControllerListDaysSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AttendanceControllerListDaysSortBy =
  (typeof AttendanceControllerListDaysSortBy)[keyof typeof AttendanceControllerListDaysSortBy];

export const AttendanceControllerListDaysSortBy = {
  date: 'date',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AttendanceControllerStudentHistoryParams = {
  sessionId: string;
};

export type ClassLevelControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: ClassLevelControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * age
   */
  age?: number;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * gender
   */
  gender?: ClassLevelControllerFindAllGender;
  /**
   * Sort by
   */
  sortBy?: ClassLevelControllerFindAllSortBy;
};

export type ClassLevelControllerFindAllSortOrder =
  (typeof ClassLevelControllerFindAllSortOrder)[keyof typeof ClassLevelControllerFindAllSortOrder];

export const ClassLevelControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ClassLevelControllerFindAllGender =
  (typeof ClassLevelControllerFindAllGender)[keyof typeof ClassLevelControllerFindAllGender];

export const ClassLevelControllerFindAllGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export type ClassLevelControllerFindAllSortBy =
  (typeof ClassLevelControllerFindAllSortBy)[keyof typeof ClassLevelControllerFindAllSortBy];

export const ClassLevelControllerFindAllSortBy = {
  id: 'id',
  age: 'age',
  code: 'code',
  name: 'name',
  gender: 'gender',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ClassLevelControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AdmissionsControllerSearchLegacyParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdmissionsControllerSearchLegacySortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * Search query (GR, phone, name, father name)
   */
  query: string;
  /**
   * Sort by
   */
  sortBy?: AdmissionsControllerSearchLegacySortBy;
};

export type AdmissionsControllerSearchLegacySortOrder =
  (typeof AdmissionsControllerSearchLegacySortOrder)[keyof typeof AdmissionsControllerSearchLegacySortOrder];

export const AdmissionsControllerSearchLegacySortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdmissionsControllerSearchLegacySortBy =
  (typeof AdmissionsControllerSearchLegacySortBy)[keyof typeof AdmissionsControllerSearchLegacySortBy];

export const AdmissionsControllerSearchLegacySortBy = {
  grNo: 'grNo',
  name: 'name',
  fathersName: 'fathersName',
  phoneNumber: 'phoneNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AdmissionsControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdmissionsControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * sessionId
   */
  sessionId?: string;
  /**
   * branchId
   */
  branchId?: string;
  /**
   * areaId
   */
  areaId?: string;
  /**
   * grNumber (exact match)
   */
  grNumber?: string;
  /**
   * name (contains)
   */
  name?: string;
  /**
   * fatherName (contains)
   */
  fatherName?: string;
  /**
   * phone (contains)
   */
  phone?: string;
  /**
   * schoolName (contains)
   */
  schoolName?: string;
  /**
   * classLevelId
   */
  classLevelId?: string;
  status?: AdmissionsControllerFindAllStatus;
  /**
   * isFeePaid
   */
  isFeePaid?: boolean;
  /**
   * Sort by
   */
  sortBy?: AdmissionsControllerFindAllSortBy;
};

export type AdmissionsControllerFindAllSortOrder =
  (typeof AdmissionsControllerFindAllSortOrder)[keyof typeof AdmissionsControllerFindAllSortOrder];

export const AdmissionsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdmissionsControllerFindAllStatus =
  (typeof AdmissionsControllerFindAllStatus)[keyof typeof AdmissionsControllerFindAllStatus];

export const AdmissionsControllerFindAllStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  MANUAL_VERIFICATION_REQUIRED: 'MANUAL_VERIFICATION_REQUIRED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export type AdmissionsControllerFindAllSortBy =
  (typeof AdmissionsControllerFindAllSortBy)[keyof typeof AdmissionsControllerFindAllSortBy];

export const AdmissionsControllerFindAllSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  isFeePaid: 'isFeePaid',
} as const;

export type AdmissionsControllerGetDashboardParams = {
  /**
   * Filter statistics by a specific session ID. If omitted, aggregates across all sessions.
   */
  sessionId?: string;
  /**
   * Filter statistics by a specific branch ID. If omitted, aggregates across all branches.
   */
  branchId?: string;
  /**
   * Number of days for the recent trend time series (recentTrend). The API returns a day-by-day series from (today - days + 1) to today. Useful for rendering admission/interaction charts.
   * @minimum 1
   * @maximum 365
   */
  days?: number;
};

export type AdmissionsControllerFindOneParams = {
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
};

export type QuestionSetControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: QuestionSetControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * sessionId
   */
  sessionId?: string;
  /**
   * classLevelId
   */
  classLevelId?: string;
  /**
   * title (contains)
   */
  title?: string;
  /**
   * Sort by
   */
  sortBy?: QuestionSetControllerFindAllSortBy;
};

export type QuestionSetControllerFindAllSortOrder =
  (typeof QuestionSetControllerFindAllSortOrder)[keyof typeof QuestionSetControllerFindAllSortOrder];

export const QuestionSetControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type QuestionSetControllerFindAllSortBy =
  (typeof QuestionSetControllerFindAllSortBy)[keyof typeof QuestionSetControllerFindAllSortBy];

export const QuestionSetControllerFindAllSortBy = {
  id: 'id',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type QuestionSetControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type LegacyStudentImportControllerFindAllParams = {
  /**
   * Skip records for pagination
   */
  skip?: number;
  /**
   * Take records for pagination
   */
  take?: number;
  /**
   * Search by name
   */
  name?: string;
  /**
   * Search by father's name
   */
  fathersName?: string;
  /**
   * Search by phone number
   */
  phoneNumber?: string;
  /**
   * Search by GR number
   */
  grNo?: string;
};
